#include "ftk_widget.idl"

typedef voidPtr FtkCheckButtonPtr;

interface FtkCheckButton : FtkWidget
{
	FtkCheckButtonPtr ftk_check_button_create(in FtkWidgetPtr parent, in int x, in int y, in int width, in int height);
	FtkCheckButtonPtr ftk_check_button_create_radio(in FtkWidgetPtr parent, in int x, in int y, in int width, in int height);
	Ret        ftk_check_button_set_icon_position(in FtkWidgetPtr thiz, in int at_right);
	int        ftk_check_button_get_checked(in FtkWidgetPtr thiz);
	Ret        ftk_check_button_set_checked(in FtkWidgetPtr thiz, in int checked);
	Ret        ftk_check_button_set_clicked_listener(in FtkWidgetPtr thiz, in FtkListenerFunc listener);
};
