#include "ftk_widget.idl"

typedef voidPtr FtkTextViewPtr;
interface FtkTextView : FtkWidget
{
	FtkTextViewPtr ftk_text_view_create(in FtkWidgetPtr parent, in int x, in int y, in int width, in int height);
	CStrPtr ftk_text_view_get_text(in FtkWidgetPtr thiz);
	Ret ftk_text_view_set_text(in FtkWidgetPtr thiz, in CStrPtr text, in int len);
	Ret ftk_text_view_insert_text(in FtkWidgetPtr thiz, in size_t pos, in CStrPtr text, in int len);
	Ret ftk_text_view_set_readonly(in FtkWidgetPtr thiz, in int ro);
};
