
#define FTK_EGL_FUNC_UNUSED(ret, func, params)
#define FTK_GLES_FUNC_UNUSED(ret, func, params)

FTK_EGL_FUNC_UNUSED(EGLint, eglGetError, (void))
FTK_EGL_FUNC(EGLDisplay, eglGetDisplay, (EGLNativeDisplayType display_id))
FTK_EGL_FUNC(EGLBoolean, eglInitialize, (EGLDisplay dpy, EGLint *major, EGLint *minor))
FTK_EGL_FUNC(EGLBoolean, eglTerminate, (EGLDisplay dpy))
FTK_EGL_FUNC_UNUSED(const char *, eglQueryString, (EGLDisplay dpy, EGLint name))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglGetConfigs, (EGLDisplay dpy, EGLConfig *configs, EGLint config_size, EGLint *num_config))
FTK_EGL_FUNC(EGLBoolean, eglChooseConfig, (EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglGetConfigAttrib, (EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint *value))
FTK_EGL_FUNC(EGLSurface, eglCreateWindowSurface, (EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list))
FTK_EGL_FUNC_UNUSED(EGLSurface, eglCreatePbufferSurface, (EGLDisplay dpy, EGLConfig config, const EGLint *attrib_list))
FTK_EGL_FUNC_UNUSED(EGLSurface, eglCreatePixmapSurface, (EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint *attrib_list))
FTK_EGL_FUNC(EGLBoolean, eglDestroySurface, (EGLDisplay dpy, EGLSurface surface))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglQuerySurface, (EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint *value))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglBindAPI, (EGLenum api))
FTK_EGL_FUNC_UNUSED(EGLenum, eglQueryAPI, (void))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglWaitClient, (void))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglReleaseThread, (void))
FTK_EGL_FUNC_UNUSED(EGLSurface, eglCreatePbufferFromClientBuffer, (EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint *attrib_list))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglSurfaceAttrib, (EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglBindTexImage, (EGLDisplay dpy, EGLSurface surface, EGLint buffer))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglReleaseTexImage, (EGLDisplay dpy, EGLSurface surface, EGLint buffer))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglSwapInterval, (EGLDisplay dpy, EGLint interval))
FTK_EGL_FUNC(EGLContext, eglCreateContext, (EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list))
FTK_EGL_FUNC(EGLBoolean, eglDestroyContext, (EGLDisplay dpy, EGLContext ctx))
FTK_EGL_FUNC(EGLBoolean, eglMakeCurrent, (EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx))
FTK_EGL_FUNC_UNUSED(EGLContext, eglGetCurrentContext, (void))
FTK_EGL_FUNC_UNUSED(EGLSurface, eglGetCurrentSurface, (EGLint readdraw))
FTK_EGL_FUNC_UNUSED(EGLDisplay, eglGetCurrentDisplay, (void))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglQueryContext, (EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint *value))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglWaitGL, (void))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglWaitNative, (EGLint engine))
FTK_EGL_FUNC(EGLBoolean, eglSwapBuffers, (EGLDisplay dpy, EGLSurface surface))
FTK_EGL_FUNC_UNUSED(EGLBoolean, eglCopyBuffers, (EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target))

#ifndef __eglMustCastToProperFunctionPointerType
typedef void (*__eglMustCastToProperFunctionPointerType)(void);
#define __eglMustCastToProperFunctionPointerType
#endif
FTK_EGL_FUNC_UNUSED(__eglMustCastToProperFunctionPointerType, eglGetProcAddress, (const char *procname))

/******************************************************************************/

FTK_GLES_FUNC_UNUSED(void, glAlphaFunc, (GLenum func, GLclampf ref))
FTK_GLES_FUNC(void, glClearColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha))
FTK_GLES_FUNC_UNUSED(void, glClearDepthf, (GLclampf depth))
FTK_GLES_FUNC_UNUSED(void, glClipPlanef, (GLenum plane, const GLfloat * equation))
FTK_GLES_FUNC(void, glColor4f, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
FTK_GLES_FUNC_UNUSED(void, glDepthRangef, (GLclampf zNear, GLclampf zFar))
FTK_GLES_FUNC_UNUSED(void, glFogf, (GLenum pname, GLfloat param))
FTK_GLES_FUNC_UNUSED(void, glFogfv, (GLenum pname, const GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glFrustumf, (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar))
FTK_GLES_FUNC_UNUSED(void, glGetClipPlanef, (GLenum pname, GLfloat eqn[4]))
FTK_GLES_FUNC_UNUSED(void, glGetFloatv, (GLenum pname, GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glGetLightfv, (GLenum light, GLenum pname, GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glGetMaterialfv, (GLenum face, GLenum pname, GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glGetTexEnvfv, (GLenum env, GLenum pname, GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glLightModelf, (GLenum pname, GLfloat param))
FTK_GLES_FUNC_UNUSED(void, glLightModelfv, (GLenum pname, const GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glLightf, (GLenum light, GLenum pname, GLfloat param))
FTK_GLES_FUNC_UNUSED(void, glLightfv, (GLenum light, GLenum pname, const GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glLineWidth, (GLfloat width))
FTK_GLES_FUNC_UNUSED(void, glLoadMatrixf, (const GLfloat * m))
FTK_GLES_FUNC_UNUSED(void, glMaterialf, (GLenum face, GLenum pname, GLfloat param))
FTK_GLES_FUNC_UNUSED(void, glMaterialfv, (GLenum face, GLenum pname, const GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glMultMatrixf, (const GLfloat * m))
FTK_GLES_FUNC_UNUSED(void, glMultiTexCoord4f, (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q))
FTK_GLES_FUNC_UNUSED(void, glNormal3f, (GLfloat nx, GLfloat ny, GLfloat nz))
FTK_GLES_FUNC(void, glOrthof, (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar))
FTK_GLES_FUNC_UNUSED(void, glPointParameterf, (GLenum pname, GLfloat param))
FTK_GLES_FUNC_UNUSED(void, glPointParameterfv, (GLenum pname, const GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glPointSize, (GLfloat size))
FTK_GLES_FUNC_UNUSED(void, glPolygonOffset, (GLfloat factor, GLfloat units))
FTK_GLES_FUNC_UNUSED(void, glRotatef, (GLfloat angle, GLfloat x, GLfloat y, GLfloat z))
FTK_GLES_FUNC_UNUSED(void, glScalef, (GLfloat x, GLfloat y, GLfloat z))
FTK_GLES_FUNC_UNUSED(void, glTexEnvf, (GLenum target, GLenum pname, GLfloat param))
FTK_GLES_FUNC_UNUSED(void, glTexEnvfv, (GLenum target, GLenum pname, const GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glTexParameterf, (GLenum target, GLenum pname, GLfloat param))
FTK_GLES_FUNC_UNUSED(void, glTexParameterfv, (GLenum target, GLenum pname, const GLfloat * params))
FTK_GLES_FUNC_UNUSED(void, glTranslatef, (GLfloat x, GLfloat y, GLfloat z))

FTK_GLES_FUNC_UNUSED(void, glActiveTexture, (GLenum texture))
FTK_GLES_FUNC_UNUSED(void, glAlphaFuncx, (GLenum func, GLclampx ref))
FTK_GLES_FUNC_UNUSED(void, glBindBuffer, (GLenum target, GLuint buffer))
FTK_GLES_FUNC(void, glBindTexture, (GLenum target, GLuint texture))
FTK_GLES_FUNC(void, glBlendFunc, (GLenum sfactor, GLenum dfactor))
FTK_GLES_FUNC_UNUSED(void, glBufferData, (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage))
FTK_GLES_FUNC_UNUSED(void, glBufferSubData, (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid * data))
FTK_GLES_FUNC(void, glClear, (GLbitfield mask))
FTK_GLES_FUNC_UNUSED(void, glClearColorx, (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha))
FTK_GLES_FUNC_UNUSED(void, glClearDepthx, (GLclampx depth))
FTK_GLES_FUNC_UNUSED(void, glClearStencil, (GLint s))
FTK_GLES_FUNC_UNUSED(void, glClientActiveTexture, (GLenum texture))
FTK_GLES_FUNC_UNUSED(void, glClipPlanex, (GLenum plane, const GLfixed * equation))
FTK_GLES_FUNC_UNUSED(void, glColor4ub, (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha))
FTK_GLES_FUNC_UNUSED(void, glColor4x, (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha))
FTK_GLES_FUNC_UNUSED(void, glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
FTK_GLES_FUNC_UNUSED(void, glColorPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer))
FTK_GLES_FUNC_UNUSED(void, glCompressedTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data))
FTK_GLES_FUNC_UNUSED(void, glCompressedTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data))
FTK_GLES_FUNC_UNUSED(void, glCopyTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))
FTK_GLES_FUNC_UNUSED(void, glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))
FTK_GLES_FUNC_UNUSED(void, glCullFace, (GLenum mode))
FTK_GLES_FUNC_UNUSED(void, glDeleteBuffers, (GLsizei n, const GLuint * buffers))
FTK_GLES_FUNC_UNUSED(void, glDeleteTextures, (GLsizei n, const GLuint * textures))
FTK_GLES_FUNC_UNUSED(void, glDepthFunc, (GLenum func))
FTK_GLES_FUNC_UNUSED(void, glDepthMask, (GLboolean flag))
FTK_GLES_FUNC_UNUSED(void, glDepthRangex, (GLclampx zNear, GLclampx zFar))
FTK_GLES_FUNC_UNUSED(void, glDisable, (GLenum cap))
FTK_GLES_FUNC_UNUSED(void, glDisableClientState, (GLenum array))
FTK_GLES_FUNC(void, glDrawArrays, (GLenum mode, GLint first, GLsizei count))
FTK_GLES_FUNC_UNUSED(void, glDrawElements, (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices))
FTK_GLES_FUNC(void, glEnable, (GLenum cap))
FTK_GLES_FUNC(void, glEnableClientState, (GLenum array))
FTK_GLES_FUNC_UNUSED(void, glFinish, (void))
FTK_GLES_FUNC_UNUSED(void, glFlush, (void))
FTK_GLES_FUNC_UNUSED(void, glFogx, (GLenum pname, GLfixed param))
FTK_GLES_FUNC_UNUSED(void, glFogxv, (GLenum pname, const GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glFrontFace, (GLenum mode))
FTK_GLES_FUNC_UNUSED(void, glFrustumx, (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar))
FTK_GLES_FUNC_UNUSED(void, glGetBooleanv, (GLenum pname, GLboolean * params))
FTK_GLES_FUNC_UNUSED(void, glGetBufferParameteriv, (GLenum target, GLenum pname, GLint * params))
FTK_GLES_FUNC_UNUSED(void, glGetClipPlanex, (GLenum pname, GLfixed eqn[4]))
FTK_GLES_FUNC_UNUSED(void, glGenBuffers, (GLsizei n, GLuint * buffers))
FTK_GLES_FUNC_UNUSED(void, glGenTextures, (GLsizei n, GLuint * textures))
FTK_GLES_FUNC_UNUSED(GLenum, glGetError, (void))
FTK_GLES_FUNC_UNUSED(void, glGetFixedv, (GLenum pname, GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glGetIntegerv, (GLenum pname, GLint * params))
FTK_GLES_FUNC_UNUSED(void, glGetLightxv, (GLenum light, GLenum pname, GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glGetMaterialxv, (GLenum face, GLenum pname, GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glGetPointerv, (GLenum pname, void **params))
FTK_GLES_FUNC_UNUSED(const GLubyte *, glGetString, (GLenum name))
FTK_GLES_FUNC_UNUSED(void, glGetTexEnviv, (GLenum env, GLenum pname, GLint * params))
FTK_GLES_FUNC_UNUSED(void, glGetTexEnvxv, (GLenum env, GLenum pname, GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glGetTexParameteriv, (GLenum target, GLenum pname, GLint * params))
FTK_GLES_FUNC_UNUSED(void, glGetTexParameterxv, (GLenum target, GLenum pname, GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glHint, (GLenum target, GLenum mode))
FTK_GLES_FUNC_UNUSED(GLboolean, glIsBuffer, (GLuint buffer))
FTK_GLES_FUNC_UNUSED(GLboolean, glIsEnabled, (GLenum cap))
FTK_GLES_FUNC_UNUSED(GLboolean, glIsTexture, (GLuint texture))
FTK_GLES_FUNC_UNUSED(void, glLightModelx, (GLenum pname, GLfixed param))
FTK_GLES_FUNC_UNUSED(void, glLightModelxv, (GLenum pname, const GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glLightx, (GLenum light, GLenum pname, GLfixed param))
FTK_GLES_FUNC_UNUSED(void, glLightxv, (GLenum light, GLenum pname, const GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glLineWidthx, (GLfixed width))
FTK_GLES_FUNC(void, glLoadIdentity, (void))
FTK_GLES_FUNC_UNUSED(void, glLoadMatrixx, (const GLfixed * m))
FTK_GLES_FUNC_UNUSED(void, glLogicOp, (GLenum opcode))
FTK_GLES_FUNC_UNUSED(void, glMaterialx, (GLenum face, GLenum pname, GLfixed param))
FTK_GLES_FUNC_UNUSED(void, glMaterialxv, (GLenum face, GLenum pname, const GLfixed * params))
FTK_GLES_FUNC(void, glMatrixMode, (GLenum mode))
FTK_GLES_FUNC_UNUSED(void, glMultMatrixx, (const GLfixed * m))
FTK_GLES_FUNC_UNUSED(void, glMultiTexCoord4x, (GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q))
FTK_GLES_FUNC_UNUSED(void, glNormal3x, (GLfixed nx, GLfixed ny, GLfixed nz))
FTK_GLES_FUNC_UNUSED(void, glNormalPointer, (GLenum type, GLsizei stride, const GLvoid * pointer))
FTK_GLES_FUNC_UNUSED(void, glOrthox, (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar))
FTK_GLES_FUNC_UNUSED(void, glPixelStorei, (GLenum pname, GLint param))
FTK_GLES_FUNC_UNUSED(void, glPointParameterx, (GLenum pname, GLfixed param))
FTK_GLES_FUNC_UNUSED(void, glPointParameterxv, (GLenum pname, const GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glPointSizex, (GLfixed size))
FTK_GLES_FUNC_UNUSED(void, glPolygonOffsetx, (GLfixed factor, GLfixed units))
FTK_GLES_FUNC_UNUSED(void, glPopMatrix, (void))
FTK_GLES_FUNC_UNUSED(void, glPushMatrix, (void))
FTK_GLES_FUNC_UNUSED(void, glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels))
FTK_GLES_FUNC_UNUSED(void, glRotatex, (GLfixed angle, GLfixed x, GLfixed y, GLfixed z))
FTK_GLES_FUNC_UNUSED(void, glSampleCoverage, (GLclampf value, GLboolean invert))
FTK_GLES_FUNC_UNUSED(void, glSampleCoveragex, (GLclampx value, GLboolean invert))
FTK_GLES_FUNC_UNUSED(void, glScalex, (GLfixed x, GLfixed y, GLfixed z))
FTK_GLES_FUNC_UNUSED(void, glScissor, (GLint x, GLint y, GLsizei width, GLsizei height))
FTK_GLES_FUNC_UNUSED(void, glShadeModel, (GLenum mode))
FTK_GLES_FUNC_UNUSED(void, glStencilFunc, (GLenum func, GLint ref, GLuint mask))
FTK_GLES_FUNC_UNUSED(void, glStencilMask, (GLuint mask))
FTK_GLES_FUNC_UNUSED(void, glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass))
FTK_GLES_FUNC(void, glTexCoordPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer))
FTK_GLES_FUNC_UNUSED(void, glTexEnvi, (GLenum target, GLenum pname, GLint param))
FTK_GLES_FUNC_UNUSED(void, glTexEnvx, (GLenum target, GLenum pname, GLfixed param))
FTK_GLES_FUNC_UNUSED(void, glTexEnviv, (GLenum target, GLenum pname, const GLint * params))
FTK_GLES_FUNC_UNUSED(void, glTexEnvxv, (GLenum target, GLenum pname, const GLfixed * params))
FTK_GLES_FUNC(void, glTexImage2D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels))
FTK_GLES_FUNC(void, glTexParameteri, (GLenum target, GLenum pname, GLint param))
FTK_GLES_FUNC_UNUSED(void, glTexParameterx, (GLenum target, GLenum pname, GLfixed param))
FTK_GLES_FUNC_UNUSED(void, glTexParameteriv, (GLenum target, GLenum pname, const GLint * params))
FTK_GLES_FUNC_UNUSED(void, glTexParameterxv, (GLenum target, GLenum pname, const GLfixed * params))
FTK_GLES_FUNC_UNUSED(void, glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels))
FTK_GLES_FUNC_UNUSED(void, glTranslatex, (GLfixed x, GLfixed y, GLfixed z))
FTK_GLES_FUNC(void, glVertexPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer))
FTK_GLES_FUNC(void, glViewport, (GLint x, GLint y, GLsizei width, GLsizei height))

FTK_GLES_FUNC_UNUSED(void, glDrawTexiOES, (GLint x, GLint y, GLint z, GLint width, GLint height))
