/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_list_view.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkListView_H
#define LUA_FtkListView_H

typedef FtkWidget FtkListView;
int tolua_ftk_list_view_init(lua_State* L);

#endif/*LUA_FtkListView_H*/

