/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_wait_box.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkWaitBox_H
#define LUA_FtkWaitBox_H

typedef FtkWidget FtkWaitBox;
int tolua_ftk_wait_box_init(lua_State* L);

#endif/*LUA_FtkWaitBox_H*/

