/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_config.h"

#ifndef LUA_FtkConfig_H
#define LUA_FtkConfig_H

int tolua_ftk_config_init(lua_State* L);

#endif/*LUA_FtkConfig_H*/

