/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_widget.h"

#ifndef LUA_FtkWidget_H
#define LUA_FtkWidget_H

int tolua_ftk_widget_init(lua_State* L);

#endif/*LUA_FtkWidget_H*/

