/*This file is generated by luagen.*/
#include "lua_ftk_bitmap_factory.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkBitmapFactory");
}

static int lua_ftk_bitmap_factory_create(lua_State* L)
{
	FtkBitmapFactory* retv;
	retv = ftk_bitmap_factory_create();
	tolua_pushusertype(L, (FtkBitmapFactory*)retv, "FtkBitmapFactory");

	return 1;
}

static int lua_ftk_bitmap_factory_load(lua_State* L)
{
	tolua_Error err = {0};
	FtkBitmap* retv;
	FtkBitmapFactory* thiz;
	const char* filename;
	int param_ok = tolua_isusertype(L, 1, "FtkBitmapFactory", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	filename = tolua_tostring(L, 2, 0);
	retv = ftk_bitmap_factory_load(thiz, filename);
	tolua_pushusertype(L, (FtkBitmap*)retv, "FtkBitmap");

	return 1;
}

static int lua_ftk_bitmap_factory_add_decoder(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkBitmapFactory* thiz;
	FtkImageDecoder* decoder;
	int param_ok = tolua_isusertype(L, 1, "FtkBitmapFactory", 0, &err) && tolua_isusertype(L, 2, "FtkImageDecoder", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	decoder = tolua_tousertype(L, 2, 0);
	retv = ftk_bitmap_factory_add_decoder(thiz, decoder);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_bitmap_factory_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkBitmapFactory* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkBitmapFactory", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_bitmap_factory_destroy(thiz);

	return 1;
}

int tolua_ftk_bitmap_factory_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkBitmapFactory", "FtkBitmapFactory", "", NULL);
	tolua_beginmodule(L, "FtkBitmapFactory");
	tolua_function(L, "Create", lua_ftk_bitmap_factory_create);
	tolua_function(L, "Load", lua_ftk_bitmap_factory_load);
	tolua_function(L, "AddDecoder", lua_ftk_bitmap_factory_add_decoder);
	tolua_function(L, "Destroy", lua_ftk_bitmap_factory_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
