/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_entry.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkEntry_H
#define LUA_FtkEntry_H

typedef FtkWidget FtkEntry;
int tolua_ftk_entry_init(lua_State* L);

#endif/*LUA_FtkEntry_H*/

