/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_display.h"

#ifndef LUA_FtkDisplay_H
#define LUA_FtkDisplay_H

int tolua_ftk_display_init(lua_State* L);

#endif/*LUA_FtkDisplay_H*/

