/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_xul.h"

#ifndef LUA_FtkXul_H
#define LUA_FtkXul_H

int tolua_ftk_xul_init(lua_State* L);

#endif/*LUA_FtkXul_H*/

