/*This file is generated by luagen.*/
#include "lua_ftk_menu_panel.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkMenuPanel");
}

static int lua_ftk_menu_panel_create(lua_State* L)
{
	FtkMenuPanel* retv;
	retv = ftk_menu_panel_create();
	tolua_pushusertype(L, (FtkMenuPanel*)retv, "FtkMenuPanel");

	return 1;
}

static int lua_ftk_menu_panel_relayout(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_menu_panel_relayout(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_menu_panel_add(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkWidget* item;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	item = tolua_tousertype(L, 2, 0);
	retv = ftk_menu_panel_add(thiz, item);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_menu_panel_remove(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkWidget* item;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	item = tolua_tousertype(L, 2, 0);
	retv = ftk_menu_panel_remove(thiz, item);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

int tolua_ftk_menu_panel_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkMenuPanel", "FtkMenuPanel", "FtkWidget", NULL);
	tolua_beginmodule(L, "FtkMenuPanel");
	tolua_function(L, "Create", lua_ftk_menu_panel_create);
	tolua_function(L, "Relayout", lua_ftk_menu_panel_relayout);
	tolua_function(L, "Add", lua_ftk_menu_panel_add);
	tolua_function(L, "Remove", lua_ftk_menu_panel_remove);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
