/*This file is generated by luagen.*/
#include "lua_ftk_scroll_bar.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkScrollBar");
}

static int lua_ftk_scroll_bar_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkScrollBar* retv;
	FtkWidget* parent;
	int x;
	int y;
	int width;
	int height;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isnumber(L, 4, 0, &err) && tolua_isnumber(L, 5, 0, &err);

	return_val_if_fail(param_ok, 0);

	parent = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	width = tolua_tonumber(L, 4, 0);
	height = tolua_tonumber(L, 5, 0);
	retv = ftk_scroll_bar_create(parent, x, y, width, height);
	tolua_pushusertype(L, (FtkScrollBar*)retv, "FtkScrollBar");

	return 1;
}

static int lua_ftk_scroll_bar_set_param(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int value;
	int max_value;
	int page_delta;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isnumber(L, 4, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	value = tolua_tonumber(L, 2, 0);
	max_value = tolua_tonumber(L, 3, 0);
	page_delta = tolua_tonumber(L, 4, 0);
	retv = ftk_scroll_bar_set_param(thiz, value, max_value, page_delta);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_scroll_bar_set_listener(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	char* listener;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	listener = (char*)tolua_tostring(L, 2, 0);
	retv = ftk_scroll_bar_set_listener(thiz, lua_ftk_widget_listener_func, listener);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_scroll_bar_get_value(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_scroll_bar_get_value(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_scroll_bar_get_max_value(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_scroll_bar_get_max_value(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_scroll_bar_inc(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_scroll_bar_inc(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_scroll_bar_dec(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_scroll_bar_dec(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_scroll_bar_pageup(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_scroll_bar_pageup(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_scroll_bar_pagedown(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_scroll_bar_pagedown(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_scroll_bar_set_value(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int value;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isnumber(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	value = tolua_tonumber(L, 2, 0);
	retv = ftk_scroll_bar_set_value(thiz, value);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

int tolua_ftk_scroll_bar_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkScrollBar", "FtkScrollBar", "FtkWidget", NULL);
	tolua_beginmodule(L, "FtkScrollBar");
	tolua_function(L, "Create", lua_ftk_scroll_bar_create);
	tolua_function(L, "SetParam", lua_ftk_scroll_bar_set_param);
	tolua_function(L, "SetListener", lua_ftk_scroll_bar_set_listener);
	tolua_function(L, "GetValue", lua_ftk_scroll_bar_get_value);
	tolua_function(L, "GetMaxValue", lua_ftk_scroll_bar_get_max_value);
	tolua_function(L, "Inc", lua_ftk_scroll_bar_inc);
	tolua_function(L, "Dec", lua_ftk_scroll_bar_dec);
	tolua_function(L, "Pageup", lua_ftk_scroll_bar_pageup);
	tolua_function(L, "Pagedown", lua_ftk_scroll_bar_pagedown);
	tolua_function(L, "SetValue", lua_ftk_scroll_bar_set_value);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
