/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_menu_item.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkMenuItem_H
#define LUA_FtkMenuItem_H

typedef FtkWidget FtkMenuItem;
int tolua_ftk_menu_item_init(lua_State* L);

#endif/*LUA_FtkMenuItem_H*/

