/*This file is generated by luagen.*/
#include "lua_ftk_window.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkWindow");
}

static int lua_ftk_window_set_focus(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkWidget* focus_widget;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	focus_widget = tolua_tousertype(L, 2, 0);
	retv = ftk_window_set_focus(thiz, focus_widget);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_get_focus(lua_State* L)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_window_get_focus(thiz);
	tolua_pushusertype(L, (FtkWidget*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_window_grab(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkWidget* grab_widget;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	grab_widget = tolua_tousertype(L, 2, 0);
	retv = ftk_window_grab(thiz, grab_widget);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_ungrab(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkWidget* grab_widget;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	grab_widget = tolua_tousertype(L, 2, 0);
	retv = ftk_window_ungrab(thiz, grab_widget);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_paint_forcely(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_window_paint_forcely(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_update(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkRect* rect;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isusertype(L, 2, "FtkRect", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	rect = tolua_tousertype(L, 2, 0);
	retv = ftk_window_update(thiz, rect);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_is_mapped(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_window_is_mapped(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_is_fullscreen(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_window_is_fullscreen(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_set_fullscreen(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int fullscreen;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isnumber(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	fullscreen = tolua_tonumber(L, 2, 0);
	retv = ftk_window_set_fullscreen(thiz, fullscreen);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_invalidate(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkRect* rect;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isusertype(L, 2, "FtkRect", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	rect = tolua_tousertype(L, 2, 0);
	retv = ftk_window_invalidate(thiz, rect);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_set_background_with_alpha(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkBitmap* bitmap;
	FtkColor bg;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isusertype(L, 2, "FtkBitmap", 0, &err) && tolua_isusertype(L, 3, "FtkColor", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	bitmap = tolua_tousertype(L, 2, 0);
	bg = *(FtkColor*)tolua_tousertype(L, 3, 0);
	retv = ftk_window_set_background_with_alpha(thiz, bitmap, bg);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_enable_update(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_window_enable_update(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_disable_update(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_window_disable_update(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_get_animation_hint(lua_State* L)
{
	tolua_Error err = {0};
	const char* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_window_get_animation_hint(thiz);
	tolua_pushstring(L, (const char*)retv);

	return 1;
}

static int lua_ftk_window_set_animation_hint(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	const char* hint;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	hint = tolua_tostring(L, 2, 0);
	retv = ftk_window_set_animation_hint(thiz, hint);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

int tolua_ftk_window_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkWindow", "FtkWindow", "FtkWidget", NULL);
	tolua_beginmodule(L, "FtkWindow");
	tolua_function(L, "SetFocus", lua_ftk_window_set_focus);
	tolua_function(L, "GetFocus", lua_ftk_window_get_focus);
	tolua_function(L, "Grab", lua_ftk_window_grab);
	tolua_function(L, "Ungrab", lua_ftk_window_ungrab);
	tolua_function(L, "PaintForcely", lua_ftk_window_paint_forcely);
	tolua_function(L, "Update", lua_ftk_window_update);
	tolua_function(L, "IsMapped", lua_ftk_window_is_mapped);
	tolua_function(L, "IsFullscreen", lua_ftk_window_is_fullscreen);
	tolua_function(L, "SetFullscreen", lua_ftk_window_set_fullscreen);
	tolua_function(L, "Invalidate", lua_ftk_window_invalidate);
	tolua_function(L, "SetBackgroundWithAlpha", lua_ftk_window_set_background_with_alpha);
	tolua_function(L, "EnableUpdate", lua_ftk_window_enable_update);
	tolua_function(L, "DisableUpdate", lua_ftk_window_disable_update);
	tolua_function(L, "GetAnimationHint", lua_ftk_window_get_animation_hint);
	tolua_function(L, "SetAnimationHint", lua_ftk_window_set_animation_hint);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
