/*This file is generated by luagen.*/
#include "lua_ftk_file_browser.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkFileBrowser");
}

static int lua_ftk_file_browser_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkFileBrowser* retv;
	int type;
	int param_ok = tolua_isnumber(L, 1, 0, &err);

	return_val_if_fail(param_ok, 0);

	type = tolua_tonumber(L, 1, 0);
	retv = ftk_file_browser_create(type);
	tolua_pushusertype(L, (FtkFileBrowser*)retv, "FtkFileBrowser");

	return 1;
}

static int lua_ftk_file_browser_set_path(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	const char* path;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	path = tolua_tostring(L, 2, 0);
	retv = ftk_file_browser_set_path(thiz, path);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_file_browser_set_filter(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	const char* mime_type;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	mime_type = tolua_tostring(L, 2, 0);
	retv = ftk_file_browser_set_filter(thiz, mime_type);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_file_browser_set_choosed_handler(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	char* on_choosed;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	on_choosed = (char*)tolua_tostring(L, 2, 0);
	retv = ftk_file_browser_set_choosed_handler(thiz, lua_ftk_file_browser_on_choosed_func, on_choosed);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_file_browser_load(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_file_browser_load(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

int tolua_ftk_file_browser_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkFileBrowser", "FtkFileBrowser", "FtkWidget", NULL);
	tolua_beginmodule(L, "FtkFileBrowser");
	tolua_function(L, "Create", lua_ftk_file_browser_create);
	tolua_function(L, "SetPath", lua_ftk_file_browser_set_path);
	tolua_function(L, "SetFilter", lua_ftk_file_browser_set_filter);
	tolua_function(L, "SetChoosedHandler", lua_ftk_file_browser_set_choosed_handler);
	tolua_function(L, "Load", lua_ftk_file_browser_load);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
