/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_status_item.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkStatusItem_H
#define LUA_FtkStatusItem_H

typedef FtkWidget FtkStatusItem;
int tolua_ftk_status_item_init(lua_State* L);

#endif/*LUA_FtkStatusItem_H*/

