/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_menu_panel.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkMenuPanel_H
#define LUA_FtkMenuPanel_H

typedef FtkWidget FtkMenuPanel;
int tolua_ftk_menu_panel_init(lua_State* L);

#endif/*LUA_FtkMenuPanel_H*/

