/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_label.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkLabel_H
#define LUA_FtkLabel_H

typedef FtkWidget FtkLabel;
int tolua_ftk_label_init(lua_State* L);

#endif/*LUA_FtkLabel_H*/

