/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_button.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkButton_H
#define LUA_FtkButton_H

typedef FtkWidget FtkButton;
int tolua_ftk_button_init(lua_State* L);

#endif/*LUA_FtkButton_H*/

