/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_list_render_default.h"
#include "lua_ftk_list_render.h"

#ifndef LUA_FtkListRenderDefault_H
#define LUA_FtkListRenderDefault_H

typedef FtkListRender FtkListRenderDefault;
int tolua_ftk_list_render_default_init(lua_State* L);

#endif/*LUA_FtkListRenderDefault_H*/

