/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_mmap.h"

#ifndef LUA_FtkMmap_H
#define LUA_FtkMmap_H

int tolua_ftk_mmap_init(lua_State* L);

#endif/*LUA_FtkMmap_H*/

