/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_dialog.h"
#include "lua_ftk_window.h"

#ifndef LUA_FtkDialog_H
#define LUA_FtkDialog_H

typedef FtkWindow FtkDialog;
int tolua_ftk_dialog_init(lua_State* L);

#endif/*LUA_FtkDialog_H*/

