/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_window.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkWindow_H
#define LUA_FtkWindow_H

typedef FtkWidget FtkWindow;
int tolua_ftk_window_init(lua_State* L);

#endif/*LUA_FtkWindow_H*/

