/*This file is generated by luagen.*/
#include "lua_ftk_dir.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkDir");
}

static int lua_ftk_dir_open(lua_State* L)
{
	tolua_Error err = {0};
	FtkDir* retv;
	const char* dir_name;
	int param_ok = tolua_isstring(L, 1, 0, &err);

	return_val_if_fail(param_ok, 0);

	dir_name = tolua_tostring(L, 1, 0);
	retv = ftk_dir_open(dir_name);
	tolua_pushusertype(L, (FtkDir*)retv, "FtkDir");

	return 1;
}

static int lua_ftk_dir_read(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkDir* dir;
	FtkFileInfo* info;
	int param_ok = tolua_isusertype(L, 1, "FtkDir", 0, &err) && tolua_isusertype(L, 2, "FtkFileInfo", 0, &err);

	return_val_if_fail(param_ok, 0);

	dir = tolua_tousertype(L, 1, 0);
	info = tolua_tousertype(L, 2, 0);
	retv = ftk_dir_read(dir, info);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_dir_close(lua_State* L)
{
	tolua_Error err = {0};
	FtkDir* dir;
	int param_ok = tolua_isusertype(L, 1, "FtkDir", 0, &err);

	return_val_if_fail(param_ok, 0);

	dir = tolua_tousertype(L, 1, 0);
	ftk_dir_close(dir);

	return 1;
}

int tolua_ftk_dir_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkDir", "FtkDir", "", NULL);
	tolua_beginmodule(L, "FtkDir");
	tolua_function(L, "Open", lua_ftk_dir_open);
	tolua_function(L, "Read", lua_ftk_dir_read);
	tolua_function(L, "Close", lua_ftk_dir_close);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
