/*This file is generated by luagen.*/
#include "lua_ftk_list_model_default.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkListModelDefault");
}

static int lua_ftk_list_model_default_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkListModel* retv;
	int init_nr;
	int param_ok = tolua_isnumber(L, 1, 0, &err);

	return_val_if_fail(param_ok, 0);

	init_nr = tolua_tonumber(L, 1, 0);
	retv = ftk_list_model_default_create(init_nr);
	tolua_pushusertype(L, (FtkListModel*)retv, "FtkListModel");

	return 1;
}

int tolua_ftk_list_model_default_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkListModelDefault", "FtkListModelDefault", "FtkListModel", NULL);
	tolua_beginmodule(L, "FtkListModelDefault");
	tolua_function(L, "Create", lua_ftk_list_model_default_create);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
