/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_group_box.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkGroupBox_H
#define LUA_FtkGroupBox_H

typedef FtkWidget FtkGroupBox;
int tolua_ftk_group_box_init(lua_State* L);

#endif/*LUA_FtkGroupBox_H*/

