/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_source.h"

#ifndef LUA_FtkSource_H
#define LUA_FtkSource_H

int tolua_ftk_source_init(lua_State* L);

#endif/*LUA_FtkSource_H*/

