/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_bitmap.h"

#ifndef LUA_FtkBitmap_H
#define LUA_FtkBitmap_H

int tolua_ftk_bitmap_init(lua_State* L);

#endif/*LUA_FtkBitmap_H*/

