/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_sprite.h"

#ifndef LUA_FtkSprite_H
#define LUA_FtkSprite_H

int tolua_ftk_sprite_init(lua_State* L);

#endif/*LUA_FtkSprite_H*/

