/*This file is generated by luagen.*/
#include "lua_ftk_main_loop.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkMainLoop");
}

static int lua_ftk_main_loop_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkMainLoop* retv;
	FtkSourcesManager* sources_manager;
	int param_ok = tolua_isusertype(L, 1, "FtkSourcesManager", 0, &err);

	return_val_if_fail(param_ok, 0);

	sources_manager = tolua_tousertype(L, 1, 0);
	retv = ftk_main_loop_create(sources_manager);
	tolua_pushusertype(L, (FtkMainLoop*)retv, "FtkMainLoop");

	return 1;
}

static int lua_ftk_main_loop_run(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkMainLoop* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkMainLoop", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_main_loop_run(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_main_loop_quit(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkMainLoop* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkMainLoop", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_main_loop_quit(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_main_loop_add_source(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkMainLoop* thiz;
	FtkSource* source;
	int param_ok = tolua_isusertype(L, 1, "FtkMainLoop", 0, &err) && tolua_isusertype(L, 2, "FtkSource", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	source = tolua_tousertype(L, 2, 0);
	retv = ftk_main_loop_add_source(thiz, source);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_main_loop_remove_source(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkMainLoop* thiz;
	FtkSource* source;
	int param_ok = tolua_isusertype(L, 1, "FtkMainLoop", 0, &err) && tolua_isusertype(L, 2, "FtkSource", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	source = tolua_tousertype(L, 2, 0);
	retv = ftk_main_loop_remove_source(thiz, source);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_main_loop_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkMainLoop* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkMainLoop", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_main_loop_destroy(thiz);

	return 1;
}

int tolua_ftk_main_loop_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkMainLoop", "FtkMainLoop", "", NULL);
	tolua_beginmodule(L, "FtkMainLoop");
	tolua_function(L, "Create", lua_ftk_main_loop_create);
	tolua_function(L, "Run", lua_ftk_main_loop_run);
	tolua_function(L, "Quit", lua_ftk_main_loop_quit);
	tolua_function(L, "AddSource", lua_ftk_main_loop_add_source);
	tolua_function(L, "RemoveSource", lua_ftk_main_loop_remove_source);
	tolua_function(L, "Destroy", lua_ftk_main_loop_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
