/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_check_button.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkCheckButton_H
#define LUA_FtkCheckButton_H

typedef FtkWidget FtkCheckButton;
int tolua_ftk_check_button_init(lua_State* L);

#endif/*LUA_FtkCheckButton_H*/

