/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_main_loop.h"

#ifndef LUA_FtkMainLoop_H
#define LUA_FtkMainLoop_H

int tolua_ftk_main_loop_init(lua_State* L);

#endif/*LUA_FtkMainLoop_H*/

