/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_source_idle.h"
#include "lua_ftk_source.h"

#ifndef LUA_FtkSourceIdle_H
#define LUA_FtkSourceIdle_H

typedef FtkSource FtkSourceIdle;
int tolua_ftk_source_idle_init(lua_State* L);

#endif/*LUA_FtkSourceIdle_H*/

