/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_scroll_bar.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkScrollBar_H
#define LUA_FtkScrollBar_H

typedef FtkWidget FtkScrollBar;
int tolua_ftk_scroll_bar_init(lua_State* L);

#endif/*LUA_FtkScrollBar_H*/

