/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_theme.h"

#ifndef LUA_FtkTheme_H
#define LUA_FtkTheme_H

int tolua_ftk_theme_init(lua_State* L);

#endif/*LUA_FtkTheme_H*/

