/*This file is generated by luagen.*/
#include "lua_ftk_mmap.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkMmap");
}

static int lua_ftk_mmap_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkMmap* retv;
	const char* filename;
	int offset;
	int size;
	int param_ok = tolua_isstring(L, 1, 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	filename = tolua_tostring(L, 1, 0);
	offset = tolua_tonumber(L, 2, 0);
	size = tolua_tonumber(L, 3, 0);
	retv = ftk_mmap_create(filename, offset, size);
	tolua_pushusertype(L, (FtkMmap*)retv, "FtkMmap");

	return 1;
}

static int lua_ftk_mmap_data(lua_State* L)
{
	tolua_Error err = {0};
	void* retv;
	FtkMmap* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkMmap", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_mmap_data(thiz);
	tolua_pushusertype(L, (void*)retv, "void");

	return 1;
}

static int lua_ftk_mmap_length(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkMmap* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkMmap", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_mmap_length(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_mmap_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkMmap* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkMmap", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_mmap_destroy(thiz);

	return 1;
}

int tolua_ftk_mmap_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkMmap", "FtkMmap", "", NULL);
	tolua_beginmodule(L, "FtkMmap");
	tolua_function(L, "Create", lua_ftk_mmap_create);
	tolua_function(L, "Data", lua_ftk_mmap_data);
	tolua_function(L, "Length", lua_ftk_mmap_length);
	tolua_function(L, "Destroy", lua_ftk_mmap_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
