/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_bitmap_factory.h"

#ifndef LUA_FtkBitmapFactory_H
#define LUA_FtkBitmapFactory_H

int tolua_ftk_bitmap_factory_init(lua_State* L);

#endif/*LUA_FtkBitmapFactory_H*/

