/*This file is generated by luagen.*/
#include "lua_ftk_source_idle.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkSourceIdle");
}

static int lua_ftk_source_idle_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkSource* retv;
	char* action;
	int param_ok = tolua_isstring(L, 1, 0, &err);

	return_val_if_fail(param_ok, 0);

	action = (char*)tolua_tostring(L, 1, 0);
	retv = ftk_source_idle_create(lua_ftk_idle_func, action);
	tolua_pushusertype(L, (FtkSource*)retv, "FtkSource");

	return 1;
}

int tolua_ftk_source_idle_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkSourceIdle", "FtkSourceIdle", "FtkSource", NULL);
	tolua_beginmodule(L, "FtkSourceIdle");
	tolua_function(L, "Create", lua_ftk_source_idle_create);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
