/*This file is generated by luagen.*/
#include "lua_ftk_image.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkImage");
}

static int lua_ftk_image_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* parent;
	int x;
	int y;
	int width;
	int height;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isnumber(L, 4, 0, &err) && tolua_isnumber(L, 5, 0, &err);

	return_val_if_fail(param_ok, 0);

	parent = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	width = tolua_tonumber(L, 4, 0);
	height = tolua_tonumber(L, 5, 0);
	retv = ftk_image_create(parent, x, y, width, height);
	tolua_pushusertype(L, (FtkWidget*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_image_set_image(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkBitmap* image;
	int param_ok = tolua_isusertype(L, 1, "FtkWidget", 0, &err) && tolua_isusertype(L, 2, "FtkBitmap", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	image = tolua_tousertype(L, 2, 0);
	retv = ftk_image_set_image(thiz, image);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

int tolua_ftk_image_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkImage", "FtkImage", "", NULL);
	tolua_beginmodule(L, "FtkImage");
	tolua_function(L, "Create", lua_ftk_image_create);
	tolua_function(L, "SetImage", lua_ftk_image_set_image);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
