/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_clipboard.h"

#ifndef LUA_FtkClipboard_H
#define LUA_FtkClipboard_H

int tolua_ftk_clipboard_init(lua_State* L);

#endif/*LUA_FtkClipboard_H*/

