/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_icon_view.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkIconView_H
#define LUA_FtkIconView_H

typedef FtkWidget FtkIconView;
int tolua_ftk_icon_view_init(lua_State* L);

#endif/*LUA_FtkIconView_H*/

