/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_status_panel.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkStatusPanel_H
#define LUA_FtkStatusPanel_H

typedef FtkWidget FtkStatusPanel;
int tolua_ftk_status_panel_init(lua_State* L);

#endif/*LUA_FtkStatusPanel_H*/

