/*This file is generated by luagen.*/
#include "lua_ftk_source_timer.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkSourceTimer");
}

static int lua_ftk_source_timer_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkSource* retv;
	int interval;
	char* action;
	int param_ok = tolua_isnumber(L, 1, 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	interval = tolua_tonumber(L, 1, 0);
	action = (char*)tolua_tostring(L, 2, 0);
	retv = ftk_source_timer_create(interval, lua_ftk_timer_func, action);
	tolua_pushusertype(L, (FtkSource*)retv, "FtkSource");

	return 1;
}

static int lua_ftk_source_timer_reset(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkSource* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkSource", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_source_timer_reset(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

int tolua_ftk_source_timer_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkSourceTimer", "FtkSourceTimer", "FtkSource", NULL);
	tolua_beginmodule(L, "FtkSourceTimer");
	tolua_function(L, "Create", lua_ftk_source_timer_create);
	tolua_function(L, "Reset", lua_ftk_source_timer_reset);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
