/*This file is generated by luagen.*/
#include "lua_ftk_list_model.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkListModel");
}

static int lua_ftk_list_model_ref(lua_State* L)
{
	tolua_Error err = {0};
	FtkListModel* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_list_model_ref(thiz);

	return 1;
}

static int lua_ftk_list_model_unref(lua_State* L)
{
	tolua_Error err = {0};
	FtkListModel* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_list_model_unref(thiz);

	return 1;
}

static int lua_ftk_list_model_enable_notify(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkListModel* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_list_model_enable_notify(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_list_model_disable_notify(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkListModel* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_list_model_disable_notify(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_list_model_add(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkListModel* thiz;
	FtkListItemInfo* item;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err) && tolua_isusertype(L, 2, "FtkListItemInfo", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	item = tolua_tousertype(L, 2, 0);
	retv = ftk_list_model_add(thiz, item);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_list_model_remove(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkListModel* thiz;
	int index;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err) && tolua_isnumber(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	index = tolua_tonumber(L, 2, 0);
	retv = ftk_list_model_remove(thiz, index);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_list_model_reset(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkListModel* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_list_model_reset(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_list_model_get_total(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkListModel* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_list_model_get_total(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_list_model_get_data(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkListModel* thiz;
	int index;
	FtkListItemInfo* ret;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err) && tolua_isnumber(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	index = tolua_tonumber(L, 2, 0);
	retv = ftk_list_model_get_data(thiz, index, (void**)&ret);
	tolua_pushnumber(L, (lua_Number)retv);
	tolua_pushusertype(L, (FtkListItemInfo*)ret, "FtkListItemInfo");

	return 1;
}

static int lua_ftk_list_model_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkListModel* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkListModel", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_list_model_destroy(thiz);

	return 1;
}

int tolua_ftk_list_model_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkListModel", "FtkListModel", "", NULL);
	tolua_beginmodule(L, "FtkListModel");
	tolua_function(L, "Ref", lua_ftk_list_model_ref);
	tolua_function(L, "Unref", lua_ftk_list_model_unref);
	tolua_function(L, "EnableNotify", lua_ftk_list_model_enable_notify);
	tolua_function(L, "DisableNotify", lua_ftk_list_model_disable_notify);
	tolua_function(L, "Add", lua_ftk_list_model_add);
	tolua_function(L, "Remove", lua_ftk_list_model_remove);
	tolua_function(L, "Reset", lua_ftk_list_model_reset);
	tolua_function(L, "GetTotal", lua_ftk_list_model_get_total);
	tolua_function(L, "GetData", lua_ftk_list_model_get_data);
	tolua_function(L, "Destroy", lua_ftk_list_model_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
