/*This file is generated by luagen.*/
#include "lua_ftk_list_render_default.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkListRenderDefault");
}

static int lua_ftk_list_render_default_create(lua_State* L)
{
	FtkListRender* retv;
	retv = ftk_list_render_default_create();
	tolua_pushusertype(L, (FtkListRender*)retv, "FtkListRender");

	return 1;
}

int tolua_ftk_list_render_default_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkListRenderDefault", "FtkListRenderDefault", "FtkListRender", NULL);
	tolua_beginmodule(L, "FtkListRenderDefault");
	tolua_function(L, "Create", lua_ftk_list_render_default_create);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
