/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_translator.h"

#ifndef LUA_FtkTranslator_H
#define LUA_FtkTranslator_H

int tolua_ftk_translator_init(lua_State* L);

#endif/*LUA_FtkTranslator_H*/

