/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_progress_bar.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkProgressBar_H
#define LUA_FtkProgressBar_H

typedef FtkWidget FtkProgressBar;
int tolua_ftk_progress_bar_init(lua_State* L);

#endif/*LUA_FtkProgressBar_H*/

