/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_list_render.h"

#ifndef LUA_FtkListRender_H
#define LUA_FtkListRender_H

int tolua_ftk_list_render_init(lua_State* L);

#endif/*LUA_FtkListRender_H*/

