/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_icon_cache.h"

#ifndef LUA_FtkIconCache_H
#define LUA_FtkIconCache_H

int tolua_ftk_icon_cache_init(lua_State* L);

#endif/*LUA_FtkIconCache_H*/

