/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_dir.h"

#ifndef LUA_FtkDir_H
#define LUA_FtkDir_H

int tolua_ftk_dir_init(lua_State* L);

#endif/*LUA_FtkDir_H*/

