/*This file is generated by luagen.*/
#include "lua_ftk_wnd_manager.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkWndManager");
}

static int lua_ftk_wnd_manager_restack(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	FtkWidget* window;
	int offset;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err) && tolua_isnumber(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	window = tolua_tousertype(L, 2, 0);
	offset = tolua_tonumber(L, 3, 0);
	retv = ftk_wnd_manager_restack(thiz, window, offset);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_grab(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	FtkWidget* window;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	window = tolua_tousertype(L, 2, 0);
	retv = ftk_wnd_manager_grab(thiz, window);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_ungrab(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	FtkWidget* window;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	window = tolua_tousertype(L, 2, 0);
	retv = ftk_wnd_manager_ungrab(thiz, window);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_add(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	FtkWidget* window;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	window = tolua_tousertype(L, 2, 0);
	retv = ftk_wnd_manager_add(thiz, window);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_remove(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	FtkWidget* window;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	window = tolua_tousertype(L, 2, 0);
	retv = ftk_wnd_manager_remove(thiz, window);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_update(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_wnd_manager_update(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_get_work_area(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	FtkRect* rect;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isusertype(L, 2, "FtkRect", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	rect = tolua_tousertype(L, 2, 0);
	retv = ftk_wnd_manager_get_work_area(thiz, rect);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_queue_event(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	FtkEvent* event;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isusertype(L, 2, "FtkEvent", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	event = tolua_tousertype(L, 2, 0);
	retv = ftk_wnd_manager_queue_event(thiz, event);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_dispatch_event(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	FtkEvent* event;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isusertype(L, 2, "FtkEvent", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	event = tolua_tousertype(L, 2, 0);
	retv = ftk_wnd_manager_dispatch_event(thiz, event);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_add_global_listener(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	char* listener;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	listener = (char*)tolua_tostring(L, 2, 0);
	retv = ftk_wnd_manager_add_global_listener(thiz, lua_ftk_listener_func, listener);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_remove_global_listener(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWndManager* thiz;
	char* listener;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	listener = (char*)tolua_tostring(L, 2, 0);
	retv = ftk_wnd_manager_remove_global_listener(thiz, lua_ftk_listener_func, listener);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_wnd_manager_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkWndManager* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkWndManager", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_wnd_manager_destroy(thiz);

	return 1;
}

int tolua_ftk_wnd_manager_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkWndManager", "FtkWndManager", "", NULL);
	tolua_beginmodule(L, "FtkWndManager");
	tolua_function(L, "Restack", lua_ftk_wnd_manager_restack);
	tolua_function(L, "Grab", lua_ftk_wnd_manager_grab);
	tolua_function(L, "Ungrab", lua_ftk_wnd_manager_ungrab);
	tolua_function(L, "Add", lua_ftk_wnd_manager_add);
	tolua_function(L, "Remove", lua_ftk_wnd_manager_remove);
	tolua_function(L, "Update", lua_ftk_wnd_manager_update);
	tolua_function(L, "GetWorkArea", lua_ftk_wnd_manager_get_work_area);
	tolua_function(L, "QueueEvent", lua_ftk_wnd_manager_queue_event);
	tolua_function(L, "DispatchEvent", lua_ftk_wnd_manager_dispatch_event);
	tolua_function(L, "AddGlobalListener", lua_ftk_wnd_manager_add_global_listener);
	tolua_function(L, "RemoveGlobalListener", lua_ftk_wnd_manager_remove_global_listener);
	tolua_function(L, "Destroy", lua_ftk_wnd_manager_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
