/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_text_view.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkTextView_H
#define LUA_FtkTextView_H

typedef FtkWidget FtkTextView;
int tolua_ftk_text_view_init(lua_State* L);

#endif/*LUA_FtkTextView_H*/

