/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_list_model.h"

#ifndef LUA_FtkListModel_H
#define LUA_FtkListModel_H

int tolua_ftk_list_model_init(lua_State* L);

#endif/*LUA_FtkListModel_H*/

