/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_typedef.h"

#ifndef LUA_FtkTypedef_H
#define LUA_FtkTypedef_H

int tolua_ftk_typedef_init(lua_State* L);

#endif/*LUA_FtkTypedef_H*/

