/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_combo_box.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkComboBox_H
#define LUA_FtkComboBox_H

typedef FtkWidget FtkComboBox;
int tolua_ftk_combo_box_init(lua_State* L);

#endif/*LUA_FtkComboBox_H*/

