/*This file is generated by luagen.*/
#include "lua_ftk_sprite.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkSprite");
}

static int lua_ftk_sprite_create(lua_State* L)
{
	FtkSprite* retv;
	retv = ftk_sprite_create();
	tolua_pushusertype(L, (FtkSprite*)retv, "FtkSprite");

	return 1;
}

static int lua_ftk_sprite_get_x(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkSprite* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkSprite", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_sprite_get_x(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_sprite_get_y(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkSprite* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkSprite", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_sprite_get_y(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_sprite_is_visible(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkSprite* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkSprite", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_sprite_is_visible(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_sprite_show(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkSprite* thiz;
	int show;
	int param_ok = tolua_isusertype(L, 1, "FtkSprite", 0, &err) && tolua_isnumber(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	show = tolua_tonumber(L, 2, 0);
	retv = ftk_sprite_show(thiz, show);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_sprite_move(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkSprite* thiz;
	int x;
	int y;
	int param_ok = tolua_isusertype(L, 1, "FtkSprite", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	retv = ftk_sprite_move(thiz, x, y);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_sprite_set_icon(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkSprite* thiz;
	FtkBitmap* icon;
	int param_ok = tolua_isusertype(L, 1, "FtkSprite", 0, &err) && tolua_isusertype(L, 2, "FtkBitmap", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	icon = tolua_tousertype(L, 2, 0);
	retv = ftk_sprite_set_icon(thiz, icon);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_sprite_set_move_listener(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkSprite* thiz;
	char* listener;
	int param_ok = tolua_isusertype(L, 1, "FtkSprite", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	listener = (char*)tolua_tostring(L, 2, 0);
	retv = ftk_sprite_set_move_listener(thiz, lua_ftk_listener_func, listener);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_sprite_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkSprite* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkSprite", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_sprite_destroy(thiz);

	return 1;
}

int tolua_ftk_sprite_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkSprite", "FtkSprite", "", NULL);
	tolua_beginmodule(L, "FtkSprite");
	tolua_function(L, "Create", lua_ftk_sprite_create);
	tolua_function(L, "GetX", lua_ftk_sprite_get_x);
	tolua_function(L, "GetY", lua_ftk_sprite_get_y);
	tolua_function(L, "IsVisible", lua_ftk_sprite_is_visible);
	tolua_function(L, "Show", lua_ftk_sprite_show);
	tolua_function(L, "Move", lua_ftk_sprite_move);
	tolua_function(L, "SetIcon", lua_ftk_sprite_set_icon);
	tolua_function(L, "SetMoveListener", lua_ftk_sprite_set_move_listener);
	tolua_function(L, "Destroy", lua_ftk_sprite_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
