/*This file is generated by luagen.*/
#include "lua_ftk_typedef.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkPoint");
	tolua_usertype(L, "FtkColor");
	tolua_usertype(L, "FtkRect");
	tolua_usertype(L, "FtkFileInfo");
	tolua_usertype(L, "FtkListItemInfo");
	tolua_usertype(L, "FtkIconViewItem");
}

int lua_ftk_point_create(lua_State* L)
{
	FtkPoint* retv = calloc(1, sizeof(FtkPoint));
	tolua_pushusertype_and_takeownership(L, (void*)retv, "FtkPoint");

	return 1;
}

static int tolua_get_FtkPoint_x(lua_State* L)
{
	lua_Number retv;
	FtkPoint* thiz = (FtkPoint*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->x;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkPoint_x(lua_State* L)
{
	FtkPoint* thiz = (FtkPoint*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->x = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkPoint_y(lua_State* L)
{
	lua_Number retv;
	FtkPoint* thiz = (FtkPoint*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->y;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkPoint_y(lua_State* L)
{
	FtkPoint* thiz = (FtkPoint*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->y = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

int lua_ftk_color_create(lua_State* L)
{
	FtkColor* retv = calloc(1, sizeof(FtkColor));
	tolua_pushusertype_and_takeownership(L, (void*)retv, "FtkColor");

	return 1;
}

static int tolua_get_FtkColor_b(lua_State* L)
{
	lua_Number retv;
	FtkColor* thiz = (FtkColor*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->b;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkColor_b(lua_State* L)
{
	FtkColor* thiz = (FtkColor*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->b = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkColor_g(lua_State* L)
{
	lua_Number retv;
	FtkColor* thiz = (FtkColor*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->g;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkColor_g(lua_State* L)
{
	FtkColor* thiz = (FtkColor*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->g = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkColor_r(lua_State* L)
{
	lua_Number retv;
	FtkColor* thiz = (FtkColor*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->r;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkColor_r(lua_State* L)
{
	FtkColor* thiz = (FtkColor*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->r = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkColor_a(lua_State* L)
{
	lua_Number retv;
	FtkColor* thiz = (FtkColor*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->a;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkColor_a(lua_State* L)
{
	FtkColor* thiz = (FtkColor*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->a = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

int lua_ftk_rect_create(lua_State* L)
{
	FtkRect* retv = calloc(1, sizeof(FtkRect));
	tolua_pushusertype_and_takeownership(L, (void*)retv, "FtkRect");

	return 1;
}

static int tolua_get_FtkRect_x(lua_State* L)
{
	lua_Number retv;
	FtkRect* thiz = (FtkRect*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->x;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkRect_x(lua_State* L)
{
	FtkRect* thiz = (FtkRect*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->x = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkRect_y(lua_State* L)
{
	lua_Number retv;
	FtkRect* thiz = (FtkRect*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->y;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkRect_y(lua_State* L)
{
	FtkRect* thiz = (FtkRect*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->y = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkRect_width(lua_State* L)
{
	lua_Number retv;
	FtkRect* thiz = (FtkRect*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->width;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkRect_width(lua_State* L)
{
	FtkRect* thiz = (FtkRect*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->width = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkRect_height(lua_State* L)
{
	lua_Number retv;
	FtkRect* thiz = (FtkRect*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->height;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkRect_height(lua_State* L)
{
	FtkRect* thiz = (FtkRect*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->height = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

int lua_ftk_file_info_create(lua_State* L)
{
	FtkFileInfo* retv = calloc(1, sizeof(FtkFileInfo));
	tolua_pushusertype_and_takeownership(L, (void*)retv, "FtkFileInfo");

	return 1;
}

static int tolua_get_FtkFileInfo_uid(lua_State* L)
{
	lua_Number retv;
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->uid;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkFileInfo_uid(lua_State* L)
{
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->uid = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkFileInfo_gid(lua_State* L)
{
	lua_Number retv;
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->gid;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkFileInfo_gid(lua_State* L)
{
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->gid = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkFileInfo_mode(lua_State* L)
{
	lua_Number retv;
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->mode;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkFileInfo_mode(lua_State* L)
{
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->mode = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkFileInfo_is_dir(lua_State* L)
{
	lua_Number retv;
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->is_dir;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkFileInfo_is_dir(lua_State* L)
{
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->is_dir = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkFileInfo_size(lua_State* L)
{
	lua_Number retv;
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->size;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkFileInfo_size(lua_State* L)
{
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->size = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkFileInfo_last_access(lua_State* L)
{
	void* retv;
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (void*)&(thiz->last_access);
	{time_t* copy=malloc(sizeof(time_t)); if(copy != NULL) memcpy(copy, &retv, sizeof(time_t));tolua_pushusertype_and_takeownership(L, (time_t*)copy, "time_t");}

	return 1;
}

static int tolua_set_FtkFileInfo_last_access(lua_State* L)
{
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->last_access = (time_t) (*(time_t*)tolua_tousertype(L, 2, 0));

	return 1;
}

static int tolua_get_FtkFileInfo_last_modify(lua_State* L)
{
	void* retv;
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (void*)&(thiz->last_modify);
	{time_t* copy=malloc(sizeof(time_t)); if(copy != NULL) memcpy(copy, &retv, sizeof(time_t));tolua_pushusertype_and_takeownership(L, (time_t*)copy, "time_t");}

	return 1;
}

static int tolua_set_FtkFileInfo_last_modify(lua_State* L)
{
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->last_modify = (time_t) (*(time_t*)tolua_tousertype(L, 2, 0));

	return 1;
}

static int tolua_get_FtkFileInfo_name(lua_State* L)
{
	char* retv;
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (char*)thiz->name;
	tolua_pushstring(L, (char*)retv);

	return 1;
}

static int tolua_set_FtkFileInfo_name(lua_State* L)
{
	FtkFileInfo* thiz = (FtkFileInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	strncpy(thiz->name, (char*)tolua_tostring(L, 2, 0), sizeof(thiz->name));

	return 1;
}

int lua_ftk_list_item_info_create(lua_State* L)
{
	FtkListItemInfo* retv = calloc(1, sizeof(FtkListItemInfo));
	tolua_pushusertype_and_takeownership(L, (void*)retv, "FtkListItemInfo");

	return 1;
}

static int tolua_get_FtkListItemInfo_text(lua_State* L)
{
	char* retv;
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (char*)thiz->text;
	tolua_pushstring(L, (char*)retv);

	return 1;
}

static int tolua_set_FtkListItemInfo_text(lua_State* L)
{
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->text = (char*) ((char*)tolua_tostring(L, 2, 0));

	return 1;
}

static int tolua_get_FtkListItemInfo_value(lua_State* L)
{
	lua_Number retv;
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->value;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkListItemInfo_value(lua_State* L)
{
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->value = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkListItemInfo_state(lua_State* L)
{
	lua_Number retv;
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->state;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkListItemInfo_state(lua_State* L)
{
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->state = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkListItemInfo_type(lua_State* L)
{
	lua_Number retv;
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (lua_Number)thiz->type;
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int tolua_set_FtkListItemInfo_type(lua_State* L)
{
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->type = (int) (tolua_tonumber(L, 2, 0));

	return 1;
}

static int tolua_get_FtkListItemInfo_left_icon(lua_State* L)
{
	void* retv;
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (void*)thiz->left_icon;
	tolua_pushusertype(L, (FtkBitmap*)retv, "FtkBitmap");

	return 1;
}

static int tolua_set_FtkListItemInfo_left_icon(lua_State* L)
{
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->left_icon = (FtkBitmap*) (tolua_tousertype(L, 2, 0));

	return 1;
}

static int tolua_get_FtkListItemInfo_right_icon(lua_State* L)
{
	void* retv;
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (void*)thiz->right_icon;
	tolua_pushusertype(L, (FtkBitmap*)retv, "FtkBitmap");

	return 1;
}

static int tolua_set_FtkListItemInfo_right_icon(lua_State* L)
{
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->right_icon = (FtkBitmap*) (tolua_tousertype(L, 2, 0));

	return 1;
}

static int tolua_get_FtkListItemInfo_user_data(lua_State* L)
{
	void* retv;
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (void*)thiz->user_data;
	tolua_pushusertype(L, (void*)retv, "void");

	return 1;
}

static int tolua_set_FtkListItemInfo_user_data(lua_State* L)
{
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->user_data = (void*) (tolua_tousertype(L, 2, 0));

	return 1;
}

static int tolua_get_FtkListItemInfo_extra_user_data(lua_State* L)
{
	void* retv;
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (void*)thiz->extra_user_data;
	tolua_pushusertype(L, (void*)retv, "void");

	return 1;
}

static int tolua_set_FtkListItemInfo_extra_user_data(lua_State* L)
{
	FtkListItemInfo* thiz = (FtkListItemInfo*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->extra_user_data = (void*) (tolua_tousertype(L, 2, 0));

	return 1;
}

int lua_ftk_icon_view_item_create(lua_State* L)
{
	FtkIconViewItem* retv = calloc(1, sizeof(FtkIconViewItem));
	tolua_pushusertype_and_takeownership(L, (void*)retv, "FtkIconViewItem");

	return 1;
}

static int tolua_get_FtkIconViewItem_text(lua_State* L)
{
	char* retv;
	FtkIconViewItem* thiz = (FtkIconViewItem*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (char*)thiz->text;
	tolua_pushstring(L, (char*)retv);

	return 1;
}

static int tolua_set_FtkIconViewItem_text(lua_State* L)
{
	FtkIconViewItem* thiz = (FtkIconViewItem*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->text = (char*) ((char*)tolua_tostring(L, 2, 0));

	return 1;
}

static int tolua_get_FtkIconViewItem_icon(lua_State* L)
{
	void* retv;
	FtkIconViewItem* thiz = (FtkIconViewItem*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (void*)thiz->icon;
	tolua_pushusertype(L, (FtkBitmap*)retv, "FtkBitmap");

	return 1;
}

static int tolua_set_FtkIconViewItem_icon(lua_State* L)
{
	FtkIconViewItem* thiz = (FtkIconViewItem*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->icon = (FtkBitmap*) (tolua_tousertype(L, 2, 0));

	return 1;
}

static int tolua_get_FtkIconViewItem_user_data(lua_State* L)
{
	char* retv;
	FtkIconViewItem* thiz = (FtkIconViewItem*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	retv = (char*)thiz->user_data;
	tolua_pushstring(L, (char*)retv);

	return 1;
}

static int tolua_set_FtkIconViewItem_user_data(lua_State* L)
{
	FtkIconViewItem* thiz = (FtkIconViewItem*)  tolua_tousertype(L, 1, 0);
	return_val_if_fail(thiz != NULL, 0);
	thiz->user_data = (char*) ((char*)tolua_tostring(L, 2, 0));

	return 1;
}

int tolua_ftk_typedef_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L, "FtkPoint", "FtkPoint", "", NULL);
	tolua_beginmodule(L, "FtkPoint");
	tolua_function(L, "Create", lua_ftk_point_create);
	tolua_variable(L, "x",tolua_get_FtkPoint_x, tolua_set_FtkPoint_x);
	tolua_variable(L, "y",tolua_get_FtkPoint_y, tolua_set_FtkPoint_y);
	tolua_endmodule(L);
	tolua_cclass(L, "FtkColor", "FtkColor", "", NULL);
	tolua_beginmodule(L, "FtkColor");
	tolua_function(L, "Create", lua_ftk_color_create);
	tolua_variable(L, "b",tolua_get_FtkColor_b, tolua_set_FtkColor_b);
	tolua_variable(L, "g",tolua_get_FtkColor_g, tolua_set_FtkColor_g);
	tolua_variable(L, "r",tolua_get_FtkColor_r, tolua_set_FtkColor_r);
	tolua_variable(L, "a",tolua_get_FtkColor_a, tolua_set_FtkColor_a);
	tolua_endmodule(L);
	tolua_cclass(L, "FtkRect", "FtkRect", "", NULL);
	tolua_beginmodule(L, "FtkRect");
	tolua_function(L, "Create", lua_ftk_rect_create);
	tolua_variable(L, "x",tolua_get_FtkRect_x, tolua_set_FtkRect_x);
	tolua_variable(L, "y",tolua_get_FtkRect_y, tolua_set_FtkRect_y);
	tolua_variable(L, "width",tolua_get_FtkRect_width, tolua_set_FtkRect_width);
	tolua_variable(L, "height",tolua_get_FtkRect_height, tolua_set_FtkRect_height);
	tolua_endmodule(L);
	tolua_cclass(L, "FtkFileInfo", "FtkFileInfo", "", NULL);
	tolua_beginmodule(L, "FtkFileInfo");
	tolua_function(L, "Create", lua_ftk_file_info_create);
	tolua_variable(L, "uid",tolua_get_FtkFileInfo_uid, tolua_set_FtkFileInfo_uid);
	tolua_variable(L, "gid",tolua_get_FtkFileInfo_gid, tolua_set_FtkFileInfo_gid);
	tolua_variable(L, "mode",tolua_get_FtkFileInfo_mode, tolua_set_FtkFileInfo_mode);
	tolua_variable(L, "is_dir",tolua_get_FtkFileInfo_is_dir, tolua_set_FtkFileInfo_is_dir);
	tolua_variable(L, "size",tolua_get_FtkFileInfo_size, tolua_set_FtkFileInfo_size);
	tolua_variable(L, "last_access",tolua_get_FtkFileInfo_last_access, tolua_set_FtkFileInfo_last_access);
	tolua_variable(L, "last_modify",tolua_get_FtkFileInfo_last_modify, tolua_set_FtkFileInfo_last_modify);
	tolua_variable(L, "name",tolua_get_FtkFileInfo_name, tolua_set_FtkFileInfo_name);
	tolua_endmodule(L);
	tolua_cclass(L, "FtkListItemInfo", "FtkListItemInfo", "", NULL);
	tolua_beginmodule(L, "FtkListItemInfo");
	tolua_function(L, "Create", lua_ftk_list_item_info_create);
	tolua_variable(L, "text",tolua_get_FtkListItemInfo_text, tolua_set_FtkListItemInfo_text);
	tolua_variable(L, "value",tolua_get_FtkListItemInfo_value, tolua_set_FtkListItemInfo_value);
	tolua_variable(L, "state",tolua_get_FtkListItemInfo_state, tolua_set_FtkListItemInfo_state);
	tolua_variable(L, "type",tolua_get_FtkListItemInfo_type, tolua_set_FtkListItemInfo_type);
	tolua_variable(L, "left_icon",tolua_get_FtkListItemInfo_left_icon, tolua_set_FtkListItemInfo_left_icon);
	tolua_variable(L, "right_icon",tolua_get_FtkListItemInfo_right_icon, tolua_set_FtkListItemInfo_right_icon);
	tolua_variable(L, "user_data",tolua_get_FtkListItemInfo_user_data, tolua_set_FtkListItemInfo_user_data);
	tolua_variable(L, "extra_user_data",tolua_get_FtkListItemInfo_extra_user_data, tolua_set_FtkListItemInfo_extra_user_data);
	tolua_endmodule(L);
	tolua_cclass(L, "FtkIconViewItem", "FtkIconViewItem", "", NULL);
	tolua_beginmodule(L, "FtkIconViewItem");
	tolua_function(L, "Create", lua_ftk_icon_view_item_create);
	tolua_variable(L, "text",tolua_get_FtkIconViewItem_text, tolua_set_FtkIconViewItem_text);
	tolua_variable(L, "icon",tolua_get_FtkIconViewItem_icon, tolua_set_FtkIconViewItem_icon);
	tolua_variable(L, "user_data",tolua_get_FtkIconViewItem_user_data, tolua_set_FtkIconViewItem_user_data);
	tolua_endmodule(L);
	tolua_constant(L, "FTK_TRUE", FTK_TRUE);
	tolua_constant(L, "FTK_FALSE", FTK_FALSE);
	tolua_constant(L, "FTK_LIST_ITEM_NORMAL", FTK_LIST_ITEM_NORMAL);
	tolua_constant(L, "FTK_LIST_ITEM_RADIO", FTK_LIST_ITEM_RADIO);
	tolua_constant(L, "FTK_LIST_ITEM_CHECK", FTK_LIST_ITEM_CHECK);
	tolua_constant(L, "FTK_LIST_ITEM_MORE", FTK_LIST_ITEM_MORE);
	tolua_constant(L, "FTK_INPUT_NORMAL", FTK_INPUT_NORMAL);
	tolua_constant(L, "FTK_INPUT_DIGIT", FTK_INPUT_DIGIT);
	tolua_constant(L, "FTK_INPUT_ALPHA", FTK_INPUT_ALPHA);
	tolua_constant(L, "FTK_INPUT_URL", FTK_INPUT_URL);
	tolua_constant(L, "FTK_INPUT_EMAIL", FTK_INPUT_EMAIL);
	tolua_constant(L, "FTK_INPUT_ALL", FTK_INPUT_ALL);
	tolua_constant(L, "FTK_FILE_BROWER_APP", FTK_FILE_BROWER_APP);
	tolua_constant(L, "FTK_FILE_BROWER_SINGLE_CHOOSER", FTK_FILE_BROWER_SINGLE_CHOOSER);
	tolua_constant(L, "FTK_FILE_BROWER_MULTI_CHOOSER", FTK_FILE_BROWER_MULTI_CHOOSER);
	tolua_constant(L, "FTK_GC_BG", FTK_GC_BG);
	tolua_constant(L, "FTK_GC_FG", FTK_GC_FG);
	tolua_constant(L, "FTK_GC_FONT", FTK_GC_FONT);
	tolua_constant(L, "FTK_GC_ALPHA", FTK_GC_ALPHA);
	tolua_constant(L, "FTK_GC_BITMAP", FTK_GC_BITMAP);
	tolua_constant(L, "FTK_GC_LINE_MASK", FTK_GC_LINE_MASK);
	tolua_constant(L, "FTK_EVT_NOP", FTK_EVT_NOP);
	tolua_constant(L, "FTK_EVT_IDLE", FTK_EVT_IDLE);
	tolua_constant(L, "FTK_EVT_TIMER", FTK_EVT_TIMER);
	tolua_constant(L, "FTK_EVT_QUIT", FTK_EVT_QUIT);
	tolua_constant(L, "FTK_EVT_KEY_UP", FTK_EVT_KEY_UP);
	tolua_constant(L, "FTK_EVT_KEY_DOWN", FTK_EVT_KEY_DOWN);
	tolua_constant(L, "FTK_EVT_MOUSE_MOVE", FTK_EVT_MOUSE_MOVE);
	tolua_constant(L, "FTK_EVT_MOUSE_DOWN", FTK_EVT_MOUSE_DOWN);
	tolua_constant(L, "FTK_EVT_MOUSE_LONG_PRESS", FTK_EVT_MOUSE_LONG_PRESS);
	tolua_constant(L, "FTK_EVT_KEY_LONG_PRESS", FTK_EVT_KEY_LONG_PRESS);
	tolua_constant(L, "FTK_EVT_MOUSE_UP", FTK_EVT_MOUSE_UP);
	tolua_constant(L, "FTK_EVT_HIDE", FTK_EVT_HIDE);
	tolua_constant(L, "FTK_EVT_SHOW", FTK_EVT_SHOW);
	tolua_constant(L, "FTK_EVT_MAP", FTK_EVT_MAP);
	tolua_constant(L, "FTK_EVT_UNMAP", FTK_EVT_UNMAP);
	tolua_constant(L, "FTK_EVT_UPDATE", FTK_EVT_UPDATE);
	tolua_constant(L, "FTK_EVT_MOVE", FTK_EVT_MOVE);
	tolua_constant(L, "FTK_EVT_RESIZE", FTK_EVT_RESIZE);
	tolua_constant(L, "FTK_EVT_MOVE_RESIZE", FTK_EVT_MOVE_RESIZE);
	tolua_constant(L, "FTK_EVT_FOCUS_IN", FTK_EVT_FOCUS_IN);
	tolua_constant(L, "FTK_EVT_FOCUS_OUT", FTK_EVT_FOCUS_OUT);
	tolua_constant(L, "FTK_EVT_ADD_CHILD", FTK_EVT_ADD_CHILD);
	tolua_constant(L, "FTK_EVT_IM_COMMIT", FTK_EVT_IM_COMMIT);
	tolua_constant(L, "FTK_EVT_IM_PREEDIT", FTK_EVT_IM_PREEDIT);
	tolua_constant(L, "FTK_EVT_IM_ACT_COMMIT", FTK_EVT_IM_ACT_COMMIT);
	tolua_constant(L, "FTK_EVT_REMOVE_CHILD", FTK_EVT_REMOVE_CHILD);
	tolua_constant(L, "FTK_EVT_WND_DESTROY", FTK_EVT_WND_DESTROY);
	tolua_constant(L, "FTK_EVT_RELAYOUT_WND", FTK_EVT_RELAYOUT_WND);
	tolua_constant(L, "FTK_EVT_ADD_SOURCE", FTK_EVT_ADD_SOURCE);
	tolua_constant(L, "FTK_EVT_REMOVE_SOURCE", FTK_EVT_REMOVE_SOURCE);
	tolua_constant(L, "FTK_EVT_THEME_CHANGED", FTK_EVT_THEME_CHANGED);
	tolua_constant(L, "FTK_EVT_LOCALE_CHANGED", FTK_EVT_LOCALE_CHANGED);
	tolua_constant(L, "FTK_EVT_DISPLAY_CHANGED", FTK_EVT_DISPLAY_CHANGED);
	tolua_constant(L, "FTK_EVT_TOP_WND_CHANGED", FTK_EVT_TOP_WND_CHANGED);
	tolua_constant(L, "FTK_EVT_WND_CONFIG_CHANGED", FTK_EVT_WND_CONFIG_CHANGED);
	tolua_constant(L, "RET_OK", RET_OK);
	tolua_constant(L, "RET_FAIL", RET_FAIL);
	tolua_constant(L, "RET_REMOVE", RET_REMOVE);
	tolua_constant(L, "RET_CONTINUE", RET_CONTINUE);
	tolua_constant(L, "RET_FOUND", RET_FOUND);
	tolua_constant(L, "RET_NEXT", RET_NEXT);
	tolua_constant(L, "RET_QUIT", RET_QUIT);
	tolua_constant(L, "RET_IGNORED", RET_IGNORED);
	tolua_constant(L, "RET_NO_TARGET", RET_NO_TARGET);
	tolua_constant(L, "RET_OUT_OF_SPACE", RET_OUT_OF_SPACE);
	tolua_constant(L, "FTK_WIDGET_NONE", FTK_WIDGET_NONE);
	tolua_constant(L, "FTK_WINDOW", FTK_WINDOW);
	tolua_constant(L, "FTK_DIALOG", FTK_DIALOG);
	tolua_constant(L, "FTK_WINDOW_MISC", FTK_WINDOW_MISC);
	tolua_constant(L, "FTK_STATUS_PANEL", FTK_STATUS_PANEL);
	tolua_constant(L, "FTK_MENU_PANEL", FTK_MENU_PANEL);
	tolua_constant(L, "FTK_MENU_ITEM", FTK_MENU_ITEM);
	tolua_constant(L, "FTK_LABEL", FTK_LABEL);
	tolua_constant(L, "FTK_BUTTON", FTK_BUTTON);
	tolua_constant(L, "FTK_IMAGE", FTK_IMAGE);
	tolua_constant(L, "FTK_ENTRY", FTK_ENTRY);
	tolua_constant(L, "FTK_PAINTER", FTK_PAINTER);
	tolua_constant(L, "FTK_WAIT_BOX", FTK_WAIT_BOX);
	tolua_constant(L, "FTK_STATUS_ITEM", FTK_STATUS_ITEM);
	tolua_constant(L, "FTK_PROGRESS_BAR", FTK_PROGRESS_BAR);
	tolua_constant(L, "FTK_GROUP_BOX", FTK_GROUP_BOX);
	tolua_constant(L, "FTK_RADIO_BUTTON", FTK_RADIO_BUTTON);
	tolua_constant(L, "FTK_CHECK_BUTTON", FTK_CHECK_BUTTON);
	tolua_constant(L, "FTK_SCROLL_VBAR", FTK_SCROLL_VBAR);
	tolua_constant(L, "FTK_SCROLL_HBAR", FTK_SCROLL_HBAR);
	tolua_constant(L, "FTK_LIST_VIEW", FTK_LIST_VIEW);
	tolua_constant(L, "FTK_ICON_VIEW", FTK_ICON_VIEW);
	tolua_constant(L, "FTK_TEXT_VIEW", FTK_TEXT_VIEW);
	tolua_constant(L, "FTK_COMBO_BOX", FTK_COMBO_BOX);
	tolua_constant(L, "FTK_WIDGET_TYPE_NR", FTK_WIDGET_TYPE_NR);
	tolua_constant(L, "FTK_LOG_V", FTK_LOG_V);
	tolua_constant(L, "FTK_LOG_D", FTK_LOG_D);
	tolua_constant(L, "FTK_LOG_E", FTK_LOG_E);
	tolua_constant(L, "FTK_WIDGET_NORMAL", FTK_WIDGET_NORMAL);
	tolua_constant(L, "FTK_WIDGET_FOCUSED", FTK_WIDGET_FOCUSED);
	tolua_constant(L, "FTK_WIDGET_ACTIVE", FTK_WIDGET_ACTIVE);
	tolua_constant(L, "FTK_WIDGET_INSENSITIVE", FTK_WIDGET_INSENSITIVE);
	tolua_constant(L, "FTK_WIDGET_STATE_NR", FTK_WIDGET_STATE_NR);
	tolua_constant(L, "FTK_ATTR_TRANSPARENT", FTK_ATTR_TRANSPARENT);
	tolua_constant(L, "FTK_ATTR_NO_FOCUS", FTK_ATTR_NO_FOCUS);
	tolua_constant(L, "FTK_ATTR_BG_CENTER", FTK_ATTR_BG_CENTER);
	tolua_constant(L, "FTK_ATTR_BG_TILE", FTK_ATTR_BG_TILE);
	tolua_constant(L, "FTK_ATTR_BG_FOUR_CORNER", FTK_ATTR_BG_FOUR_CORNER);
	tolua_constant(L, "FTK_ATTR_INSENSITIVE", FTK_ATTR_INSENSITIVE);
	tolua_constant(L, "FTK_ATTR_FOCUSED", FTK_ATTR_FOCUSED);
	tolua_constant(L, "FTK_ATTR_IGNORE_CLOSE", FTK_ATTR_IGNORE_CLOSE);
	tolua_constant(L, "FTK_ATTR_QUIT_WHEN_CLOSE", FTK_ATTR_QUIT_WHEN_CLOSE);
	tolua_constant(L, "FTK_ATTR_AUTO_LAYOUT", FTK_ATTR_AUTO_LAYOUT);
	tolua_constant(L, "FTK_ATTR_POPUP", FTK_ATTR_POPUP);
	tolua_constant(L, "FTK_KEY_SPACE", FTK_KEY_SPACE);
	tolua_constant(L, "FTK_KEY_EXCLAM", FTK_KEY_EXCLAM);
	tolua_constant(L, "FTK_KEY_QUOTEDBL", FTK_KEY_QUOTEDBL);
	tolua_constant(L, "FTK_KEY_NUMBERSIGN", FTK_KEY_NUMBERSIGN);
	tolua_constant(L, "FTK_KEY_DOLLAR", FTK_KEY_DOLLAR);
	tolua_constant(L, "FTK_KEY_PERCENT", FTK_KEY_PERCENT);
	tolua_constant(L, "FTK_KEY_AMPERSAND", FTK_KEY_AMPERSAND);
	tolua_constant(L, "FTK_KEY_APOSTROPHE", FTK_KEY_APOSTROPHE);
	tolua_constant(L, "FTK_KEY_QUOTERIGHT", FTK_KEY_QUOTERIGHT);
	tolua_constant(L, "FTK_KEY_PARENLEFT", FTK_KEY_PARENLEFT);
	tolua_constant(L, "FTK_KEY_PARENRIGHT", FTK_KEY_PARENRIGHT);
	tolua_constant(L, "FTK_KEY_ASTERISK", FTK_KEY_ASTERISK);
	tolua_constant(L, "FTK_KEY_PLUS", FTK_KEY_PLUS);
	tolua_constant(L, "FTK_KEY_COMMA", FTK_KEY_COMMA);
	tolua_constant(L, "FTK_KEY_MINUS", FTK_KEY_MINUS);
	tolua_constant(L, "FTK_KEY_PERIOD", FTK_KEY_PERIOD);
	tolua_constant(L, "FTK_KEY_SLASH", FTK_KEY_SLASH);
	tolua_constant(L, "FTK_KEY_0", FTK_KEY_0);
	tolua_constant(L, "FTK_KEY_1", FTK_KEY_1);
	tolua_constant(L, "FTK_KEY_2", FTK_KEY_2);
	tolua_constant(L, "FTK_KEY_3", FTK_KEY_3);
	tolua_constant(L, "FTK_KEY_4", FTK_KEY_4);
	tolua_constant(L, "FTK_KEY_5", FTK_KEY_5);
	tolua_constant(L, "FTK_KEY_6", FTK_KEY_6);
	tolua_constant(L, "FTK_KEY_7", FTK_KEY_7);
	tolua_constant(L, "FTK_KEY_8", FTK_KEY_8);
	tolua_constant(L, "FTK_KEY_9", FTK_KEY_9);
	tolua_constant(L, "FTK_KEY_COLON", FTK_KEY_COLON);
	tolua_constant(L, "FTK_KEY_SEMICOLON", FTK_KEY_SEMICOLON);
	tolua_constant(L, "FTK_KEY_LESS", FTK_KEY_LESS);
	tolua_constant(L, "FTK_KEY_EQUAL", FTK_KEY_EQUAL);
	tolua_constant(L, "FTK_KEY_GREATER", FTK_KEY_GREATER);
	tolua_constant(L, "FTK_KEY_QUESTION", FTK_KEY_QUESTION);
	tolua_constant(L, "FTK_KEY_AT", FTK_KEY_AT);
	tolua_constant(L, "FTK_KEY_A", FTK_KEY_A);
	tolua_constant(L, "FTK_KEY_B", FTK_KEY_B);
	tolua_constant(L, "FTK_KEY_C", FTK_KEY_C);
	tolua_constant(L, "FTK_KEY_D", FTK_KEY_D);
	tolua_constant(L, "FTK_KEY_E", FTK_KEY_E);
	tolua_constant(L, "FTK_KEY_F", FTK_KEY_F);
	tolua_constant(L, "FTK_KEY_G", FTK_KEY_G);
	tolua_constant(L, "FTK_KEY_H", FTK_KEY_H);
	tolua_constant(L, "FTK_KEY_I", FTK_KEY_I);
	tolua_constant(L, "FTK_KEY_J", FTK_KEY_J);
	tolua_constant(L, "FTK_KEY_K", FTK_KEY_K);
	tolua_constant(L, "FTK_KEY_L", FTK_KEY_L);
	tolua_constant(L, "FTK_KEY_M", FTK_KEY_M);
	tolua_constant(L, "FTK_KEY_N", FTK_KEY_N);
	tolua_constant(L, "FTK_KEY_O", FTK_KEY_O);
	tolua_constant(L, "FTK_KEY_P", FTK_KEY_P);
	tolua_constant(L, "FTK_KEY_Q", FTK_KEY_Q);
	tolua_constant(L, "FTK_KEY_R", FTK_KEY_R);
	tolua_constant(L, "FTK_KEY_S", FTK_KEY_S);
	tolua_constant(L, "FTK_KEY_T", FTK_KEY_T);
	tolua_constant(L, "FTK_KEY_U", FTK_KEY_U);
	tolua_constant(L, "FTK_KEY_V", FTK_KEY_V);
	tolua_constant(L, "FTK_KEY_W", FTK_KEY_W);
	tolua_constant(L, "FTK_KEY_X", FTK_KEY_X);
	tolua_constant(L, "FTK_KEY_Y", FTK_KEY_Y);
	tolua_constant(L, "FTK_KEY_Z", FTK_KEY_Z);
	tolua_constant(L, "FTK_KEY_BRACKETLEFT", FTK_KEY_BRACKETLEFT);
	tolua_constant(L, "FTK_KEY_BACKSLASH", FTK_KEY_BACKSLASH);
	tolua_constant(L, "FTK_KEY_BRACKETRIGHT", FTK_KEY_BRACKETRIGHT);
	tolua_constant(L, "FTK_KEY_ASCIICIRCUM", FTK_KEY_ASCIICIRCUM);
	tolua_constant(L, "FTK_KEY_UNDERSCORE", FTK_KEY_UNDERSCORE);
	tolua_constant(L, "FTK_KEY_QUOTELEFT", FTK_KEY_QUOTELEFT);
	tolua_constant(L, "FTK_KEY_GRAVE", FTK_KEY_GRAVE);
	tolua_constant(L, "FTK_KEY_LEFTBRACE", FTK_KEY_LEFTBRACE);
	tolua_constant(L, "FTK_KEY_OR", FTK_KEY_OR);
	tolua_constant(L, "FTK_KEY_RIGHTBRACE", FTK_KEY_RIGHTBRACE);
	tolua_constant(L, "FTK_KEY_NOT", FTK_KEY_NOT);
	tolua_constant(L, "FTK_KEY_DOT", FTK_KEY_DOT);
	tolua_constant(L, "FTK_KEY_HOME", FTK_KEY_HOME);
	tolua_constant(L, "FTK_KEY_LEFT", FTK_KEY_LEFT);
	tolua_constant(L, "FTK_KEY_UP", FTK_KEY_UP);
	tolua_constant(L, "FTK_KEY_RIGHT", FTK_KEY_RIGHT);
	tolua_constant(L, "FTK_KEY_DOWN", FTK_KEY_DOWN);
	tolua_constant(L, "FTK_KEY_PRIOR", FTK_KEY_PRIOR);
	tolua_constant(L, "FTK_KEY_PAGEUP", FTK_KEY_PAGEUP);
	tolua_constant(L, "FTK_KEY_NEXT", FTK_KEY_NEXT);
	tolua_constant(L, "FTK_KEY_PAGEDOWN", FTK_KEY_PAGEDOWN);
	tolua_constant(L, "FTK_KEY_END", FTK_KEY_END);
	tolua_constant(L, "FTK_KEY_BEGIN", FTK_KEY_BEGIN);
	tolua_constant(L, "FTK_KEY_INSERT", FTK_KEY_INSERT);
	tolua_constant(L, "FTK_KEY_ENTER", FTK_KEY_ENTER);
	tolua_constant(L, "FTK_KEY_TAB", FTK_KEY_TAB);
	tolua_constant(L, "FTK_KEY_ESC", FTK_KEY_ESC);
	tolua_constant(L, "FTK_KEY_RIGHTCTRL", FTK_KEY_RIGHTCTRL);
	tolua_constant(L, "FTK_KEY_LEFTCTRL", FTK_KEY_LEFTCTRL);
	tolua_constant(L, "FTK_KEY_RIGHTALT", FTK_KEY_RIGHTALT);
	tolua_constant(L, "FTK_KEY_LEFTALT", FTK_KEY_LEFTALT);
	tolua_constant(L, "FTK_KEY_RIGHTSHIFT", FTK_KEY_RIGHTSHIFT);
	tolua_constant(L, "FTK_KEY_LEFTSHIFT", FTK_KEY_LEFTSHIFT);
	tolua_constant(L, "FTK_KEY_DELETE", FTK_KEY_DELETE);
	tolua_constant(L, "FTK_KEY_F1", FTK_KEY_F1);
	tolua_constant(L, "FTK_KEY_F2", FTK_KEY_F2);
	tolua_constant(L, "FTK_KEY_F3", FTK_KEY_F3);
	tolua_constant(L, "FTK_KEY_F4", FTK_KEY_F4);
	tolua_constant(L, "FTK_KEY_F5", FTK_KEY_F5);
	tolua_constant(L, "FTK_KEY_F6", FTK_KEY_F6);
	tolua_constant(L, "FTK_KEY_F7", FTK_KEY_F7);
	tolua_constant(L, "FTK_KEY_F8", FTK_KEY_F8);
	tolua_constant(L, "FTK_KEY_F9", FTK_KEY_F9);
	tolua_constant(L, "FTK_KEY_F10", FTK_KEY_F10);
	tolua_constant(L, "FTK_KEY_CAPSLOCK", FTK_KEY_CAPSLOCK);
	tolua_constant(L, "FTK_KEY_BACKSPACE", FTK_KEY_BACKSPACE);
	tolua_constant(L, "FTK_KEY_SEND", FTK_KEY_SEND);
	tolua_constant(L, "FTK_KEY_REPLY", FTK_KEY_REPLY);
	tolua_constant(L, "FTK_KEY_SAVE", FTK_KEY_SAVE);
	tolua_constant(L, "FTK_KEY_BATTERY", FTK_KEY_BATTERY);
	tolua_constant(L, "FTK_KEY_BLUETOOTH", FTK_KEY_BLUETOOTH);
	tolua_constant(L, "FTK_KEY_WLAN", FTK_KEY_WLAN);
	tolua_constant(L, "FTK_KEY_POWER", FTK_KEY_POWER);
	tolua_constant(L, "FTK_KEY_MENU", FTK_KEY_MENU);
	tolua_constant(L, "FTK_BG_NORMAL", FTK_BG_NORMAL);
	tolua_constant(L, "FTK_BG_TILE", FTK_BG_TILE);
	tolua_constant(L, "FTK_BG_CENTER", FTK_BG_CENTER);
	tolua_constant(L, "FTK_BG_FOUR_CORNER", FTK_BG_FOUR_CORNER);
	tolua_endmodule(L);


	return 1;
}
