/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_app_window.h"
#include "lua_ftk_window.h"

#ifndef LUA_FtkAppWindow_H
#define LUA_FtkAppWindow_H

typedef FtkWindow FtkAppWindow;
int tolua_ftk_app_window_init(lua_State* L);

#endif/*LUA_FtkAppWindow_H*/

