/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_list_model_default.h"
#include "lua_ftk_list_model.h"

#ifndef LUA_FtkListModelDefault_H
#define LUA_FtkListModelDefault_H

typedef FtkListModel FtkListModelDefault;
int tolua_ftk_list_model_default_init(lua_State* L);

#endif/*LUA_FtkListModelDefault_H*/

