/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_file.h"

#ifndef LUA_FtkFile_H
#define LUA_FtkFile_H

int tolua_ftk_file_init(lua_State* L);

#endif/*LUA_FtkFile_H*/

