/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_image.h"

#ifndef LUA_FtkImage_H
#define LUA_FtkImage_H

int tolua_ftk_image_init(lua_State* L);

#endif/*LUA_FtkImage_H*/

