/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_painter.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkPainter_H
#define LUA_FtkPainter_H

typedef FtkWidget FtkPainter;
int tolua_ftk_painter_init(lua_State* L);

#endif/*LUA_FtkPainter_H*/

