/*This file is generated by luagen.*/
#include "lua_ftk_theme.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkTheme");
}

static int lua_ftk_theme_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkTheme* retv;
	int init_default;
	int param_ok = tolua_isnumber(L, 1, 0, &err);

	return_val_if_fail(param_ok, 0);

	init_default = tolua_tonumber(L, 1, 0);
	retv = ftk_theme_create(init_default);
	tolua_pushusertype(L, (FtkTheme*)retv, "FtkTheme");

	return 1;
}

static int lua_ftk_theme_parse_file(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkTheme* thiz;
	const char* filename;
	int param_ok = tolua_isusertype(L, 1, "FtkTheme", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	filename = tolua_tostring(L, 2, 0);
	retv = ftk_theme_parse_file(thiz, filename);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_theme_parse_data(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkTheme* thiz;
	const char* data;
	int length;
	int param_ok = tolua_isusertype(L, 1, "FtkTheme", 0, &err) && tolua_isstring(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	data = tolua_tostring(L, 2, 0);
	length = tolua_tonumber(L, 3, 0);
	retv = ftk_theme_parse_data(thiz, data, length);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_theme_load_image(lua_State* L)
{
	tolua_Error err = {0};
	FtkBitmap* retv;
	FtkTheme* thiz;
	const char* filename;
	int param_ok = tolua_isusertype(L, 1, "FtkTheme", 0, &err) && tolua_isstring(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	filename = tolua_tostring(L, 2, 0);
	retv = ftk_theme_load_image(thiz, filename);
	tolua_pushusertype(L, (FtkBitmap*)retv, "FtkBitmap");

	return 1;
}

static int lua_ftk_theme_get_bg(lua_State* L)
{
	tolua_Error err = {0};
	FtkBitmap* retv;
	FtkTheme* thiz;
	FtkWidgetType type;
	FtkWidgetState state;
	int param_ok = tolua_isusertype(L, 1, "FtkTheme", 0, &err) && tolua_isusertype(L, 2, "FtkWidgetType", 0, &err) && tolua_isusertype(L, 3, "FtkWidgetState", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	type = *(FtkWidgetType*)tolua_tousertype(L, 2, 0);
	state = *(FtkWidgetState*)tolua_tousertype(L, 3, 0);
	retv = ftk_theme_get_bg(thiz, type, state);
	tolua_pushusertype(L, (FtkBitmap*)retv, "FtkBitmap");

	return 1;
}

static int lua_ftk_theme_get_bg_color(lua_State* L)
{
	tolua_Error err = {0};
	FtkColor retv;
	FtkTheme* thiz;
	FtkWidgetType type;
	FtkWidgetState state;
	int param_ok = tolua_isusertype(L, 1, "FtkTheme", 0, &err) && tolua_isusertype(L, 2, "FtkWidgetType", 0, &err) && tolua_isusertype(L, 3, "FtkWidgetState", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	type = *(FtkWidgetType*)tolua_tousertype(L, 2, 0);
	state = *(FtkWidgetState*)tolua_tousertype(L, 3, 0);
	retv = ftk_theme_get_bg_color(thiz, type, state);
	{FtkColor* copy=malloc(sizeof(FtkColor)); if(copy != NULL) memcpy(copy, &retv, sizeof(FtkColor));tolua_pushusertype_and_takeownership(L, (FtkColor*)copy, "FtkColor");}

	return 1;
}

static int lua_ftk_theme_get_fg_color(lua_State* L)
{
	tolua_Error err = {0};
	FtkColor retv;
	FtkTheme* thiz;
	FtkWidgetType type;
	FtkWidgetState state;
	int param_ok = tolua_isusertype(L, 1, "FtkTheme", 0, &err) && tolua_isusertype(L, 2, "FtkWidgetType", 0, &err) && tolua_isusertype(L, 3, "FtkWidgetState", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	type = *(FtkWidgetType*)tolua_tousertype(L, 2, 0);
	state = *(FtkWidgetState*)tolua_tousertype(L, 3, 0);
	retv = ftk_theme_get_fg_color(thiz, type, state);
	{FtkColor* copy=malloc(sizeof(FtkColor)); if(copy != NULL) memcpy(copy, &retv, sizeof(FtkColor));tolua_pushusertype_and_takeownership(L, (FtkColor*)copy, "FtkColor");}

	return 1;
}

static int lua_ftk_theme_get_border_color(lua_State* L)
{
	tolua_Error err = {0};
	FtkColor retv;
	FtkTheme* thiz;
	FtkWidgetType type;
	FtkWidgetState state;
	int param_ok = tolua_isusertype(L, 1, "FtkTheme", 0, &err) && tolua_isusertype(L, 2, "FtkWidgetType", 0, &err) && tolua_isusertype(L, 3, "FtkWidgetState", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	type = *(FtkWidgetType*)tolua_tousertype(L, 2, 0);
	state = *(FtkWidgetState*)tolua_tousertype(L, 3, 0);
	retv = ftk_theme_get_border_color(thiz, type, state);
	{FtkColor* copy=malloc(sizeof(FtkColor)); if(copy != NULL) memcpy(copy, &retv, sizeof(FtkColor));tolua_pushusertype_and_takeownership(L, (FtkColor*)copy, "FtkColor");}

	return 1;
}

static int lua_ftk_theme_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkTheme* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkTheme", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_theme_destroy(thiz);

	return 1;
}

int tolua_ftk_theme_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkTheme", "FtkTheme", "", NULL);
	tolua_beginmodule(L, "FtkTheme");
	tolua_function(L, "Create", lua_ftk_theme_create);
	tolua_function(L, "ParseFile", lua_ftk_theme_parse_file);
	tolua_function(L, "ParseData", lua_ftk_theme_parse_data);
	tolua_function(L, "LoadImage", lua_ftk_theme_load_image);
	tolua_function(L, "GetBg", lua_ftk_theme_get_bg);
	tolua_function(L, "GetBgColor", lua_ftk_theme_get_bg_color);
	tolua_function(L, "GetFgColor", lua_ftk_theme_get_fg_color);
	tolua_function(L, "GetBorderColor", lua_ftk_theme_get_border_color);
	tolua_function(L, "Destroy", lua_ftk_theme_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
