/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_source_timer.h"
#include "lua_ftk_source.h"

#ifndef LUA_FtkSourceTimer_H
#define LUA_FtkSourceTimer_H

typedef FtkSource FtkSourceTimer;
int tolua_ftk_source_timer_init(lua_State* L);

#endif/*LUA_FtkSourceTimer_H*/

