/*This file is generated by luagen.*/
#include "lua_ftk_clipboard.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkClipboard");
}

static int lua_ftk_clipboard_has_data(lua_State* L)
{
	int retv;
	retv = ftk_clipboard_has_data();
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_clipboard_set_text(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	const char* text;
	int param_ok = tolua_isstring(L, 1, 0, &err);

	return_val_if_fail(param_ok, 0);

	text = tolua_tostring(L, 1, 0);
	retv = ftk_clipboard_set_text(text);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_clipboard_get_text(lua_State* L)
{
	Ret retv;
	const char* text;
	retv = ftk_clipboard_get_text(&text);
	tolua_pushnumber(L, (lua_Number)retv);
	tolua_pushstring(L, (const char*)text);

	return 1;
}

int tolua_ftk_clipboard_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkClipboard", "FtkClipboard", "", NULL);
	tolua_beginmodule(L, "FtkClipboard");
	tolua_function(L, "HasData", lua_ftk_clipboard_has_data);
	tolua_function(L, "SetText", lua_ftk_clipboard_set_text);
	tolua_function(L, "GetText", lua_ftk_clipboard_get_text);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
