/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_popup_menu.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkPopupMenu_H
#define LUA_FtkPopupMenu_H

typedef FtkWidget FtkPopupMenu;
int tolua_ftk_popup_menu_init(lua_State* L);

#endif/*LUA_FtkPopupMenu_H*/

