/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_file_browser.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkFileBrowser_H
#define LUA_FtkFileBrowser_H

typedef FtkWidget FtkFileBrowser;
int tolua_ftk_file_browser_init(lua_State* L);

#endif/*LUA_FtkFileBrowser_H*/

