/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_wnd_manager.h"

#ifndef LUA_FtkWndManager_H
#define LUA_FtkWndManager_H

int tolua_ftk_wnd_manager_init(lua_State* L);

#endif/*LUA_FtkWndManager_H*/

